# Generated by Django 5.2.16 on 2026-07-18 15:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField()),
                ('metric', models.CharField(max_length=80)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('source_event', models.CharField(max_length=120)),
                ('source_object_id', models.CharField(max_length=100)),
                ('value', models.BigIntegerField(default=1)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('occurred_at', 'id'),
                'indexes': [models.Index(fields=['metric', 'occurred_at'], name='analytics_metric_time_idx'), models.Index(fields=['actor_id', 'occurred_at'], name='analytics_actor_time_idx'), models.Index(fields=['source_event', 'source_object_id'], name='analytics_source_obj_idx')],
                'constraints': [models.UniqueConstraint(fields=('event_id', 'metric'), name='analytics_event_metric_unique')],
            },
        ),
        migrations.CreateModel(
            name='DailyActiveLearner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('user_id', models.UUIDField()),
                ('first_event_id', models.UUIDField()),
            ],
            options={
                'indexes': [models.Index(fields=['day', 'user_id'], name='analytics_dau_day_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('day', 'user_id'), name='analytics_daily_active_user_unique')],
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('metric', models.CharField(max_length=80)),
                ('dimensions_key', models.CharField(max_length=64)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('value', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('day', 'metric', 'dimensions_key'),
                'indexes': [models.Index(fields=['metric', 'day'], name='analytics_daily_metric_idx')],
                'constraints': [models.UniqueConstraint(fields=('day', 'metric', 'dimensions_key'), name='analytics_daily_dimension_unique')],
            },
        ),
    ]
