# Generated by Django 5.2.16 on 2026-07-18 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_code', models.CharField(max_length=60)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('previewed', 'Previewed'), ('completed', 'Completed'), ('expired', 'Expired'), ('failed', 'Failed')], default='previewed', max_length=12)),
                ('estimated_rows', models.PositiveIntegerField(default=0)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('truncated', models.BooleanField(default=False)),
                ('confirmation_digest', models.CharField(editable=False, max_length=64)),
                ('content_digest', models.CharField(blank=True, editable=False, max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['requested_by', '-created_at'], name='reports_user_time_idx'), models.Index(fields=['report_code', '-created_at'], name='reports_code_time_idx')],
            },
        ),
    ]
