# Generated by Django 5.2.16 on 2026-07-18 03:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('external_event_id', models.CharField(max_length=180)),
                ('event_type', models.CharField(max_length=80)),
                ('occurred_at', models.DateTimeField()),
                ('payload_digest', models.CharField(max_length=64)),
                ('normalized_data', models.JSONField()),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('processing', 'Processing'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='verified', max_length=16)),
                ('processing_error', models.CharField(blank=True, max_length=240)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'ordering': ('-received_at', '-id'),
                'indexes': [models.Index(fields=['status', 'received_at'], name='provider_event_state_idx'), models.Index(fields=['provider', 'event_type', '-occurred_at'], name='provider_event_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_event_id'), name='provider_event_dedup_unique')],
            },
        ),
        migrations.CreateModel(
            name='ProviderObjectLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('object_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('subscription', 'Subscription'), ('invoice', 'Invoice')], max_length=20)),
                ('internal_id', models.UUIDField()),
                ('external_id', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'external_id'], name='provider_link_external_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'object_type', 'internal_id'), name='provider_link_internal_unique'), models.UniqueConstraint(fields=('provider', 'object_type', 'external_id'), name='provider_link_external_unique')],
            },
        ),
        migrations.CreateModel(
            name='WebhookAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('payload_digest', models.CharField(max_length=64)),
                ('verified', models.BooleanField(default=False)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-received_at', '-id'),
                'indexes': [models.Index(fields=['provider', 'verified', '-received_at'], name='webhook_attempt_state_idx')],
            },
        ),
    ]
