# Generated by Django 5.2.16 on 2026-08-22 19:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0002_remove_creatorscope_edu_scope_has_capability_and_more'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_key', models.CharField(max_length=255)),
                ('subject_key', models.CharField(max_length=255)),
                ('subject_label_snapshot', models.CharField(max_length=220)),
                ('source_type', models.CharField(choices=[('sheet', 'Sheet question'), ('quiz', 'Quiz'), ('practice', 'Practice'), ('mix', 'Mix'), ('ai', 'AI questions'), ('active_study', 'Active Study'), ('review', 'Review Bank'), ('weekly_recall', 'Weekly Recall'), ('other', 'Other')], max_length=24)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('source_label_snapshot', models.CharField(blank=True, max_length=255)),
                ('source_question_index', models.PositiveIntegerField(blank=True, null=True)),
                ('prompt_snapshot', models.TextField()),
                ('explanation_snapshot', models.TextField(blank=True)),
                ('options_snapshot', models.JSONField(default=list)),
                ('correct_option_ids_snapshot', models.JSONField(default=list)),
                ('state', models.CharField(choices=[('active_review', 'Active review'), ('hidden_review', 'Hidden review'), ('mastered', 'Mastered')], default='active_review', max_length=16)),
                ('mastery_level', models.PositiveSmallIntegerField(default=0)),
                ('mistake_count', models.PositiveIntegerField(default=0)),
                ('review_correct_count', models.PositiveIntegerField(default=0)),
                ('review_incorrect_count', models.PositiveIntegerField(default=0)),
                ('relearning_count', models.PositiveIntegerField(default=0)),
                ('first_mistake_at', models.DateTimeField()),
                ('last_mistake_at', models.DateTimeField()),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_question_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_bank_items', to='questions.questionversion')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_bank_items', to='questions.question')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_bank_items', to='education.educationnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_bank_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_mistake_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MistakeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('sheet', 'Sheet question'), ('quiz', 'Quiz'), ('practice', 'Practice'), ('mix', 'Mix'), ('ai', 'AI questions'), ('active_study', 'Active Study'), ('review', 'Review Bank'), ('weekly_recall', 'Weekly Recall'), ('other', 'Other')], max_length=24)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('source_label_snapshot', models.CharField(blank=True, max_length=255)),
                ('source_question_index', models.PositiveIntegerField(blank=True, null=True)),
                ('prompt_snapshot', models.TextField()),
                ('selected_answer_snapshot', models.JSONField(default=list)),
                ('correct_answer_snapshot', models.JSONField(default=list)),
                ('answered_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_events', to=settings.AUTH_USER_MODEL)),
                ('review_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mistake_events', to='review.reviewitem')),
            ],
            options={
                'ordering': ('-answered_at', '-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WeeklyRecallQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('selected_option_ids', models.JSONField(blank=True, default=list)),
                ('was_correct', models.BooleanField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('review_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_recall_questions', to='review.reviewitem')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReviewAnswerLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField()),
                ('context', models.CharField(choices=[('review_bank', 'Review Bank'), ('weekly_recall', 'Weekly Recall')], max_length=16)),
                ('selected_option_ids', models.JSONField(default=list)),
                ('was_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_answer_history', to=settings.AUTH_USER_MODEL)),
                ('review_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_history', to='review.reviewitem')),
                ('weekly_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answer_logs', to='review.weeklyrecallquestion')),
            ],
            options={
                'ordering': ('-answered_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WeeklyRecallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_key', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=12)),
                ('total_questions', models.PositiveSmallIntegerField(default=0)),
                ('correct_answers', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_recall_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='weeklyrecallquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='review.weeklyrecallsession'),
        ),
        migrations.AddIndex(
            model_name='reviewitem',
            index=models.Index(fields=['user', 'state', '-last_mistake_at'], name='review_item_user_state_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewitem',
            index=models.Index(fields=['user', 'state', 'subject_key'], name='review_item_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewitem',
            index=models.Index(fields=['user', 'state', 'next_review_at'], name='review_item_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewitem',
            constraint=models.UniqueConstraint(fields=('user', 'canonical_key'), name='review_item_user_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='reviewitem',
            constraint=models.CheckConstraint(condition=models.Q(('mastery_level__gte', 0), ('mastery_level__lte', 4)), name='review_item_mastery_valid'),
        ),
        migrations.AddIndex(
            model_name='mistakeevent',
            index=models.Index(fields=['user', '-answered_at'], name='mistake_event_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='mistakeevent',
            index=models.Index(fields=['user', 'source_type', '-answered_at'], name='mistake_event_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='mistakeevent',
            constraint=models.UniqueConstraint(fields=('user', 'event_key'), name='mistake_event_user_key_unique'),
        ),
        migrations.AddIndex(
            model_name='reviewanswerlog',
            index=models.Index(fields=['user', '-answered_at'], name='review_answer_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewanswerlog',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='review_answer_user_key_unique'),
        ),
        migrations.AddIndex(
            model_name='weeklyrecallsession',
            index=models.Index(fields=['user', 'week_key', 'status'], name='weekly_recall_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='weeklyrecallsession',
            constraint=models.UniqueConstraint(fields=('user', 'week_key'), name='weekly_recall_user_week_unique'),
        ),
        migrations.AddIndex(
            model_name='weeklyrecallquestion',
            index=models.Index(fields=['session', 'position'], name='weekly_question_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='weeklyrecallquestion',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='weekly_question_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='weeklyrecallquestion',
            constraint=models.UniqueConstraint(fields=('session', 'review_item'), name='weekly_question_item_unique'),
        ),
    ]
