# Generated by Django 5.2.17 on 2026-09-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_backfill_assessment_mistakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistakeevent',
            name='correct_option_ids_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mistakeevent',
            name='explanation_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mistakeevent',
            name='options_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mistakeevent',
            name='question_type_snapshot',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='mistakeevent',
            name='question_version_id_snapshot',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mistakeevent',
            name='selected_option_ids_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mistakeevent',
            name='source_page_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mistakeevent',
            name='subject_label_snapshot',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
