# Generated by Django 5.2.16 on 2026-08-31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduledJobState",
            fields=[
                ("code", models.CharField(max_length=80, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("claim_token", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "next_run_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_succeeded_at", models.DateTimeField(blank=True, null=True)),
                ("last_failed_at", models.DateTimeField(blank=True, null=True)),
                ("last_duration_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                ("run_count", models.PositiveBigIntegerField(default=0)),
                ("failure_count", models.PositiveBigIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, max_length=120)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("next_run_at", "code"),
                "indexes": [
                    models.Index(fields=["status", "next_run_at"], name="ops_job_due_idx")
                ],
            },
        ),
    ]
