# Generated by Django 5.2.16 on 2026-07-18 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_generalize_auth_attempt_throttling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('title_en', models.CharField(max_length=120)),
                ('title_ar', models.CharField(max_length=120)),
                ('metric', models.CharField(default='learning_xp', max_length=40)),
                ('period', models.CharField(choices=[('all_time', 'All time'), ('monthly', 'Monthly')], max_length=16)),
                ('tie_strategy', models.CharField(choices=[('competition', 'Competition ranking'), ('dense', 'Dense ranking')], default='competition', max_length=16)),
                ('scope', models.CharField(default='global', max_length=32)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='RankingProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ranking_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('included', models.BooleanField(default=True)),
                ('display_mode', models.CharField(choices=[('full_name', 'Full name'), ('initials', 'Initials'), ('anonymous', 'Anonymous')], default='initials', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RankingSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('definition_revision', models.PositiveBigIntegerField()),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('building', 'Building'), ('published', 'Published'), ('failed', 'Failed')], max_length=12)),
                ('participant_count', models.PositiveBigIntegerField(default=0)),
                ('source_fact_count', models.PositiveBigIntegerField(default=0)),
                ('rules_snapshot', models.JSONField(default=dict)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='rankings.rankingdefinition')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('score', models.BigIntegerField()),
                ('evidence_count', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='rankings.rankingsnapshot')),
            ],
            options={
                'ordering': ('position', 'user_id'),
            },
        ),
        migrations.CreateModel(
            name='RankingFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_transaction_id', models.UUIDField(unique=True)),
                ('source_key', models.CharField(max_length=180)),
                ('points', models.SmallIntegerField()),
                ('category', models.CharField(max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ranking_facts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['is_valid', 'occurred_at', 'user'], name='rank_fact_time_user_idx'), models.Index(fields=['user', 'is_valid', 'occurred_at'], name='rank_fact_user_time_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='rankingsnapshot',
            index=models.Index(fields=['definition', 'status', '-generated_at'], name='rank_snapshot_current_idx'),
        ),
        migrations.AddConstraint(
            model_name='rankingsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('error', ''), ('generated_at__isnull', False), ('status', 'published')), models.Q(('error__gt', ''), ('status', 'failed')), models.Q(('error', ''), ('generated_at__isnull', True), ('status', 'building')), _connector='OR'), name='rank_snapshot_status_consistent'),
        ),
        migrations.AddIndex(
            model_name='rankingentry',
            index=models.Index(fields=['snapshot', 'position'], name='rank_entry_position_idx'),
        ),
        migrations.AddIndex(
            model_name='rankingentry',
            index=models.Index(fields=['user', 'snapshot'], name='rank_entry_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='rankingentry',
            constraint=models.UniqueConstraint(fields=('snapshot', 'user'), name='rank_entry_user_unique'),
        ),
    ]
