# Generated by Django 5.2.16 on 2026-07-15 16:07

import apps.files.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('pdf', 'PDF document'), ('audio', 'Audio')], max_length=16)),
                ('blob', models.FileField(max_length=512, upload_to=apps.files.models.managed_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(db_index=True, max_length=64)),
                ('validation_status', models.CharField(choices=[('ready', 'Validated'), ('rejected', 'Rejected')], default='ready', max_length=16)),
                ('scan_status', models.CharField(choices=[('not_configured', 'Scanner not configured'), ('pending', 'Pending scan'), ('clean', 'Clean'), ('quarantined', 'Quarantined'), ('failed', 'Scan failed')], default='not_configured', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['owner', '-created_at'], name='files_owner_created_idx'), models.Index(fields=['validation_status', 'scan_status'], name='files_processing_idx')],
            },
        ),
    ]
