# Generated by Django 5.2.17 on 2026-09-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_managed_file_scan_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedfile',
            name='pdf_page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
