# Generated by Django 5.2.17 on 2026-09-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_managedfile_pdf_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedfile',
            name='kind',
            field=models.CharField(choices=[('pdf', 'PDF document'), ('audio', 'Audio'), ('avatar', 'Profile avatar'), ('workspace_media', 'Paper Workspace media')], max_length=16),
        ),
    ]
