# Generated by Django 5.2.17 on 2026-09-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_paper_workspace_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedfile',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
