# Generated by Django 5.2.17 on 2026-10-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_managedfile_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedfile',
            name='kind',
            field=models.CharField(choices=[('pdf', 'PDF document'), ('audio', 'Audio'), ('avatar', 'Profile avatar'), ('workspace_media', 'Paper Workspace media'), ('practice_image', 'Practice slide image')], max_length=16),
        ),
    ]
