# Generated by Django 5.2.16 on 2026-07-18 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_generalize_auth_attempt_throttling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCounter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_counter', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('unread_count', models.PositiveBigIntegerField(default=0)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('account', 'Account'), ('learning', 'Learning'), ('achievement', 'Achievement'), ('community', 'Community'), ('moderation', 'Moderation'), ('platform', 'Platform')], max_length=20)),
                ('template_key', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(max_length=320)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_route', models.CharField(blank=True, max_length=300)),
                ('is_required', models.BooleanField(default=False)),
                ('deduplication_key', models.CharField(max_length=220)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('in_app', 'In app'), ('email', 'Email (future)'), ('push', 'Push (future)')], max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], max_length=12)),
                ('provider_reference', models.CharField(blank=True, max_length=160)),
                ('failure_reason', models.CharField(blank=True, max_length=240)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('account', 'Account'), ('learning', 'Learning'), ('achievement', 'Achievement'), ('community', 'Community'), ('moderation', 'Moderation'), ('platform', 'Platform')], max_length=20)),
                ('channel', models.CharField(choices=[('in_app', 'In app'), ('email', 'Email (future)'), ('push', 'Push (future)')], max_length=12)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at', '-created_at'], name='notify_user_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'category', '-created_at'], name='notify_user_category_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['target_type', 'target_id'], name='notify_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('recipient', 'deduplication_key'), name='notification_recipient_dedup_unique'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['channel', 'status', 'created_at'], name='notify_delivery_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('notification', 'channel'), name='notification_delivery_unique'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'channel'), name='notification_preference_unique'),
        ),
    ]
