# Generated by Django 5.2.16 on 2026-07-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('account', 'Account'), ('learning', 'Learning'), ('achievement', 'Achievement'), ('community', 'Community'), ('moderation', 'Moderation'), ('platform', 'Platform'), ('billing', 'Billing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='category',
            field=models.CharField(choices=[('account', 'Account'), ('learning', 'Learning'), ('achievement', 'Achievement'), ('community', 'Community'), ('moderation', 'Moderation'), ('platform', 'Platform'), ('billing', 'Billing')], max_length=20),
        ),
    ]
