# Generated by Django 5.2.16 on 2026-07-17 20:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySpace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_type', models.CharField(choices=[('lesson', 'Lesson'), ('learning_object', 'Learning object'), ('question', 'Question'), ('quiz', 'Quiz')], max_length=24)),
                ('context_id', models.UUIDField()),
                ('context_title', models.CharField(max_length=220)),
                ('context_route', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=12)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_community_spaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_type', models.CharField(choices=[('lesson', 'Lesson'), ('learning_object', 'Learning object'), ('question', 'Question'), ('quiz', 'Quiz')], max_length=24)),
                ('context_id', models.UUIDField()),
                ('context_title', models.CharField(max_length=220)),
                ('context_route', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=220)),
                ('body', models.TextField()),
                ('body_digest', models.CharField(editable=False, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('locked', 'Locked'), ('author_deleted', 'Deleted by author'), ('moderator_removed', 'Removed by moderator')], default='active', max_length=20)),
                ('removal_reason', models.TextField(blank=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('comment_count', models.PositiveBigIntegerField(default=0)),
                ('client_request_id', models.UUIDField()),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_discussions', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discussions', to='community.communityspace')),
            ],
            options={
                'ordering': ('-last_activity_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('body_digest', models.CharField(editable=False, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('author_deleted', 'Deleted by author'), ('moderator_removed', 'Removed by moderator')], default='active', max_length=20)),
                ('removal_reason', models.TextField(blank=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('client_request_id', models.UUIDField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='community.comment')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='community.discussion')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DiscussionRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField()),
                ('title', models.CharField(max_length=220)),
                ('body', models.TextField()),
                ('reason', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('author_deleted', 'Deleted by author'), ('moderator_removed', 'Removed by moderator'), ('restored', 'Restored'), ('locked', 'Locked'), ('unlocked', 'Unlocked')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='community.discussion')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discussion_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('revision',),
            },
        ),
        migrations.CreateModel(
            name='SpaceMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Space moderator')], default='member', max_length=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=12)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_membership_invitations', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.communityspace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_space_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('joined_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SpaceMembershipHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('invited', 'Invited'), ('role_changed', 'Role changed'), ('revoked', 'Revoked'), ('restored', 'Restored')], max_length=16)),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Space moderator')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_membership_actions', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='community.spacemembership')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_history', to='community.communityspace')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CommentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField()),
                ('body', models.TextField()),
                ('reason', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('author_deleted', 'Deleted by author'), ('moderator_removed', 'Removed by moderator'), ('restored', 'Restored')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='community.comment')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('revision',),
                'constraints': [models.UniqueConstraint(fields=('comment', 'revision'), name='comment_revision_unique')],
            },
        ),
        migrations.CreateModel(
            name='CommunityRateBucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('discussion_create', 'Create discussion'), ('comment_create', 'Create comment'), ('content_edit', 'Edit content')], max_length=24)),
                ('window_started_at', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_rate_buckets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['action', 'window_started_at'], name='community_rate_cleanup_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'action', 'window_started_at'), name='community_rate_bucket_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='communityspace',
            index=models.Index(fields=['owner', 'status', '-updated_at'], name='space_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='communityspace',
            index=models.Index(fields=['context_type', 'context_id', 'status'], name='space_context_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='communityspace',
            constraint=models.UniqueConstraint(fields=('owner', 'context_type', 'context_id'), name='community_space_owner_context_unique'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['context_type', 'context_id', 'status', '-last_activity_at'], name='discussion_context_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['space', 'status', '-last_activity_at'], name='discussion_space_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['author', 'status', '-updated_at'], name='discussion_author_state_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['author', 'body_digest', '-created_at'], name='discussion_duplicate_idx'),
        ),
        migrations.AddConstraint(
            model_name='discussion',
            constraint=models.UniqueConstraint(fields=('author', 'client_request_id'), name='discussion_author_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='discussion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', True), ('status__in', ('active', 'locked'))), models.Q(('deleted_at__isnull', False), ('status__in', ('author_deleted', 'moderator_removed'))), _connector='OR'), name='discussion_delete_status_consistent'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['discussion', 'status', 'created_at', 'id'], name='comment_discussion_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'status', 'created_at'], name='comment_reply_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'body_digest', '-created_at'], name='comment_duplicate_idx'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('author', 'client_request_id'), name='comment_author_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', True), ('status', 'active')), models.Q(('deleted_at__isnull', False), ('status__in', ('author_deleted', 'moderator_removed'))), _connector='OR'), name='comment_delete_status_consistent'),
        ),
        migrations.AddConstraint(
            model_name='discussionrevision',
            constraint=models.UniqueConstraint(fields=('discussion', 'revision'), name='discussion_revision_unique'),
        ),
        migrations.AddIndex(
            model_name='spacemembership',
            index=models.Index(fields=['user', 'status', 'space'], name='space_member_user_idx'),
        ),
        migrations.AddIndex(
            model_name='spacemembership',
            index=models.Index(fields=['space', 'status', 'role'], name='space_member_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='spacemembership',
            constraint=models.UniqueConstraint(fields=('space', 'user'), name='community_space_member_unique'),
        ),
        migrations.AddConstraint(
            model_name='spacemembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('status', 'active')), models.Q(('revoked_at__isnull', False), ('status', 'revoked')), _connector='OR'), name='community_membership_status_consistent'),
        ),
        migrations.AddIndex(
            model_name='spacemembershiphistory',
            index=models.Index(fields=['space', 'created_at'], name='space_history_time_idx'),
        ),
    ]
