# Generated by Django 5.2.16 on 2026-07-18 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalCapability',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='OperationalRole',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('capabilities', models.ManyToManyField(related_name='roles', to='administration.operationalcapability')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='OperationalRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_roles_granted', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='administration.operationalrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user_id', 'role_id'),
                'indexes': [models.Index(fields=['role', 'user'], name='admin_role_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='administration_user_role_unique')],
            },
        ),
    ]
