# Generated by Django 5.2.17 on 2026-09-26 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGroupPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory_group', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('default_practical_group', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('D1', 'D1'), ('D2', 'D2')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_group_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyGroupPracticalOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('general_pathology', 'general_pathology'), ('microbiology', 'microbiology'), ('pharmacology', 'pharmacology'), ('oral_histology', 'oral_histology'), ('conservative_endodontics_1', 'conservative_endodontics_1'), ('fixed_prosthodontics_1', 'fixed_prosthodontics_1'), ('removable_prosthodontics_1', 'removable_prosthodontics_1')], max_length=40)),
                ('schedule_set', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('practical_group', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('D1', 'D1'), ('D2', 'D2')], max_length=2)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_overrides', to='class_schedule.mygrouppreference')),
            ],
            options={
                'ordering': ('subject',),
            },
        ),
        migrations.AddConstraint(
            model_name='mygrouppreference',
            constraint=models.CheckConstraint(condition=models.Q(('theory_group__in', ('A', 'B'))), name='my_group_theory_group_valid'),
        ),
        migrations.AddConstraint(
            model_name='mygrouppreference',
            constraint=models.CheckConstraint(condition=models.Q(('default_practical_group__in', ('A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'D1', 'D2'))), name='my_group_default_practical_valid'),
        ),
        migrations.AddConstraint(
            model_name='mygrouppracticaloverride',
            constraint=models.UniqueConstraint(fields=('preference', 'subject'), name='my_group_override_one_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='mygrouppracticaloverride',
            constraint=models.CheckConstraint(condition=models.Q(('subject__in', ('general_pathology', 'microbiology', 'pharmacology', 'oral_histology', 'conservative_endodontics_1', 'fixed_prosthodontics_1', 'removable_prosthodontics_1'))), name='my_group_override_subject_valid'),
        ),
        migrations.AddConstraint(
            model_name='mygrouppracticaloverride',
            constraint=models.CheckConstraint(condition=models.Q(('schedule_set__in', ('A', 'B'))), name='my_group_override_set_valid'),
        ),
        migrations.AddConstraint(
            model_name='mygrouppracticaloverride',
            constraint=models.CheckConstraint(condition=models.Q(('practical_group__in', ('A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'D1', 'D2'))), name='my_group_override_group_valid'),
        ),
    ]
