# Generated by Django 5.2.17 on 2026-09-26 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mygrouppreference',
            name='my_group_default_practical_valid',
        ),
        migrations.AddField(
            model_name='mygrouppreference',
            name='academic_year',
            field=models.CharField(choices=[('year-1', 'Year 1'), ('year-2', 'Year 2')], default='year-2', max_length=8),
        ),
        migrations.AlterField(
            model_name='mygrouppreference',
            name='default_practical_group',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('D1', 'D1'), ('D2', 'D2'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2),
        ),
        migrations.AddConstraint(
            model_name='mygrouppreference',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('academic_year', 'year-2'), ('default_practical_group__in', ('A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'D1', 'D2'))), models.Q(('academic_year', 'year-1'), ('default_practical_group__in', ('A', 'B', 'C', 'D'))), _connector='OR'), name='my_group_practical_matches_year'),
        ),
    ]
