# Generated by Django 5.2.16 on 2026-07-15 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='content.learningobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'id'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='progress_bookmark_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'learning_object'), name='progress_bookmark_unique')],
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], max_length=16)),
                ('completion_percent', models.PositiveSmallIntegerField(default=0)),
                ('position', models.JSONField(blank=True, default=dict)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_records', to='content.learningobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_records', to='content.learningobjectversion')),
            ],
            options={
                'ordering': ('-updated_at', 'id'),
                'indexes': [models.Index(fields=['user', 'status', '-updated_at'], name='progress_resume_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'learning_object'), name='progress_learning_unique'), models.CheckConstraint(condition=models.Q(('completion_percent__lte', 100)), name='progress_percent_lte_100'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'in_progress')), models.Q(('completed_at__isnull', False), ('completion_percent', 100), ('status', 'completed')), _connector='OR'), name='progress_completion_consistent')],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField()),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_progress', to='education.educationnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-completed_at',),
                'indexes': [models.Index(fields=['user', '-completed_at'], name='progress_lesson_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson'), name='progress_lesson_unique')],
            },
        ),
    ]
