# Generated by Django 5.2.16 on 2026-07-17 17:24

import decimal
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_at', models.DateTimeField()),
                ('interval_days', models.PositiveIntegerField(default=1)),
                ('ease_factor', models.DecimalField(decimal_places=2, default=decimal.Decimal('2.50'), max_digits=3)),
                ('repetitions', models.PositiveSmallIntegerField(default=0)),
                ('lapses', models.PositiveSmallIntegerField(default=0)),
                ('last_was_correct', models.BooleanField(default=False)),
                ('last_reviewed_at', models.DateTimeField()),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_schedules', to='questions.questionversion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_schedules', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('due_at', 'id'),
                'indexes': [models.Index(fields=['user', 'due_at'], name='review_user_due_idx'), models.Index(fields=['user', 'repetitions', 'due_at'], name='review_mastery_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='review_user_question_unique'), models.CheckConstraint(condition=models.Q(('ease_factor__gte', 1.3), ('ease_factor__lte', 3.0)), name='review_ease_factor_valid')],
            },
        ),
        migrations.CreateModel(
            name='QuestionReviewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_id', models.UUIDField()),
                ('attempt_question_id', models.UUIDField()),
                ('was_correct', models.BooleanField()),
                ('previous_state', models.JSONField(default=dict)),
                ('new_state', models.JSONField(default=dict)),
                ('reviewed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.question')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.questionversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_review_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-reviewed_at', 'id'),
                'indexes': [models.Index(fields=['user', '-reviewed_at'], name='review_history_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('result_id', 'question'), name='review_result_question_unique')],
            },
        ),
    ]
