# Generated by Django 5.2.16 on 2026-07-15 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('review_note', models.TextField(blank=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_learning_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LearningObjectVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('content_type', models.CharField(choices=[('pdf', 'PDF document'), ('audio', 'Audio'), ('video', 'Video metadata')], max_length=32)),
                ('title', models.CharField(max_length=220)),
                ('summary', models.TextField(blank=True)),
                ('language', models.CharField(default='en', max_length=12)),
                ('allow_download', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_object_versions', to='education.educationnode')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_learning_object_versions', to=settings.AUTH_USER_MODEL)),
                ('learning_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='content.learningobject')),
            ],
            options={
                'ordering': ('-version_number',),
            },
        ),
        migrations.CreateModel(
            name='LearningObjectAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('primary', 'Primary file'), ('transcript', 'Transcript'), ('caption', 'Caption'), ('cover', 'Cover')], max_length=16)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('managed_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_object_assets', to='files.managedfile')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='content.learningobjectversion')),
            ],
            options={
                'ordering': ('role', 'position', 'id'),
            },
        ),
        migrations.AddField(
            model_name='learningobject',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for', to='content.learningobjectversion'),
        ),
        migrations.AddField(
            model_name='learningobject',
            name='published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_for', to='content.learningobjectversion'),
        ),
        migrations.AddIndex(
            model_name='learningobjectversion',
            index=models.Index(fields=['academic_node', 'content_type', '-created_at'], name='content_node_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningobjectversion',
            constraint=models.UniqueConstraint(fields=('learning_object', 'version_number'), name='content_version_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='learningobjectversion',
            constraint=models.CheckConstraint(condition=models.Q(('available_from__isnull', True), ('available_until__isnull', True), ('available_until__gt', models.F('available_from')), _connector='OR'), name='content_availability_order'),
        ),
        migrations.AddIndex(
            model_name='learningobjectasset',
            index=models.Index(fields=['managed_file', 'role'], name='content_file_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningobjectasset',
            constraint=models.UniqueConstraint(fields=('version', 'role', 'position'), name='content_asset_position_unique'),
        ),
        migrations.AddIndex(
            model_name='learningobject',
            index=models.Index(fields=['owner', 'workflow_status', '-updated_at'], name='content_owner_flow_idx'),
        ),
        migrations.AddIndex(
            model_name='learningobject',
            index=models.Index(fields=['archived_at', '-published_at'], name='content_publication_idx'),
        ),
    ]
