# Generated by Django 5.2.16 on 2026-08-28 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='learningobject',
            index=models.Index(fields=['position', 'updated_at'], name='content_position_idx'),
        ),
    ]
