# Generated by Django 5.2.17 on 2026-09-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("content", "0002_learningobject_position_and_more")]

    operations = [
        migrations.CreateModel(
            name="ActiveStudySettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled", models.BooleanField(default=False)),
                ("total_pdf_pages", models.PositiveIntegerField(blank=True, null=True)),
                ("excluded_start_pages", models.PositiveIntegerField(default=0)),
                ("excluded_end_pages", models.PositiveIntegerField(default=0)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sheet", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="active_study_settings", to="content.learningobject")),
            ],
            options={"indexes": [models.Index(fields=["enabled"], name="content_active_enabled_idx")]},
        )
    ]
