# Generated by Django 5.2.17 on 2026-09-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("content", "0003_active_study_settings")]

    operations = [
        migrations.CreateModel(
            name="ActiveStudyQuestionContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("difficulty", models.CharField(choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")], max_length=12)),
                ("payload", models.JSONField()),
                ("plan_signature", models.JSONField()),
                ("checkpoint_question_count", models.PositiveIntegerField()),
                ("final_exam_question_count", models.PositiveIntegerField()),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_active_study_question_content", to="accounts.user")),
                ("sheet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="active_study_question_content", to="content.learningobject")),
                ("updated_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="updated_active_study_question_content", to="accounts.user")),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("sheet", "difficulty"), name="active_study_content_sheet_difficulty_unique")],
                "indexes": [models.Index(fields=("sheet", "difficulty"), name="content_active_q_scope_idx")],
            },
        )
    ]
