# Generated by Django 5.2.17 on 2026-09-13 05:54

import django.db.models.deletion
from django.db import migrations, models


def backfill_active_study_source_versions(apps, schema_editor):
    del schema_editor
    LearningObjectVersion = apps.get_model("content", "LearningObjectVersion")
    ActiveStudySettings = apps.get_model("content", "ActiveStudySettings")
    ActiveStudyQuestionContent = apps.get_model("content", "ActiveStudyQuestionContent")

    for version in LearningObjectVersion.objects.filter(page_count__isnull=True).iterator():
        value = (version.metadata or {}).get("page_count")
        if isinstance(value, int) and not isinstance(value, bool) and 1 <= value <= 10_000:
            LearningObjectVersion.objects.filter(id=version.id, page_count__isnull=True).update(
                page_count=value
            )

    for settings in ActiveStudySettings.objects.filter(source_version__isnull=True).select_related(
        "sheet"
    ):
        source_id = settings.sheet.published_version_id or settings.sheet.current_version_id
        if source_id:
            ActiveStudySettings.objects.filter(
                sheet_id=settings.sheet_id, source_version__isnull=True
            ).update(source_version_id=source_id)

    for content in ActiveStudyQuestionContent.objects.filter(
        source_version__isnull=True
    ).select_related("sheet"):
        source_id = content.sheet.published_version_id or content.sheet.current_version_id
        if source_id:
            ActiveStudyQuestionContent.objects.filter(
                id=content.id, source_version__isnull=True
            ).update(source_version_id=source_id)


def noop_reverse(apps, schema_editor):
    del apps, schema_editor


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_backfill_catalog_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='activestudyquestioncontent',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_study_question_sources', to='content.learningobjectversion'),
        ),
        migrations.AddField(
            model_name='activestudysettings',
            name='page_count_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activestudysettings',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_study_settings_sources', to='content.learningobjectversion'),
        ),
        migrations.AddField(
            model_name='learningobjectversion',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_active_study_source_versions, noop_reverse),
    ]
