# Generated by Django 5.2.17 on 2026-09-15 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_learningobjectasset_role'),
        ('files', '0003_managedfile_pdf_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='activestudysettings',
            name='edition',
            field=models.CharField(default='university', max_length=16),
        ),
        migrations.AddField(
            model_name='catalogdocument',
            name='edition',
            field=models.CharField(default='university', max_length=16),
        ),
        migrations.AlterField(
            model_name='activestudysettings',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_study_settings_set', to='content.learningobject'),
        ),
        migrations.AlterField(
            model_name='catalogdocument',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_documents', to='content.learningobjectversion'),
        ),
        migrations.AlterField(
            model_name='learningobjectasset',
            name='role',
            field=models.CharField(choices=[('primary', 'Primary file'), ('summary', 'Sheet summary PDF'), ('lockin_primary', 'Lock-in edition PDF'), ('lockin_summary', 'Lock-in edition summary PDF'), ('transcript', 'Transcript'), ('caption', 'Caption'), ('cover', 'Cover')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='activestudysettings',
            constraint=models.UniqueConstraint(fields=('sheet', 'edition'), name='content_active_sheet_edition_unique'),
        ),
        migrations.AddConstraint(
            model_name='catalogdocument',
            constraint=models.UniqueConstraint(fields=('version', 'edition'), name='content_catalog_version_edition_unique'),
        ),
    ]
