# Generated by Django 5.2.17 on 2026-10-07 17:35

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0011_activestudysettings_question_counts"),
        ("files", "0005_managedfile_duration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalSheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "active_study_status",
                    models.CharField(
                        choices=[("unavailable", "Not available")],
                        default="unavailable",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "managed_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personal_sheet",
                        to="files.managedfile",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_sheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personal_sheets",
                        to="content.catalogsubject",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="PersonalSheetWorkspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("state", models.JSONField(blank=True, default=dict)),
                ("revision", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sheet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace",
                        to="content.personalsheet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalSheetWorkspaceReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                ("request_digest", models.CharField(max_length=64)),
                ("response_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="content.personalsheetworkspace",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="personalsheet",
            index=models.Index(
                fields=["owner", "subject", "-created_at"], name="content_personal_sheet_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="personalsheet",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("title"),
                models.F("owner"),
                models.F("subject"),
                name="personal_sheet_owner_subject_title_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="personalsheetworkspacereceipt",
            constraint=models.UniqueConstraint(
                fields=("workspace", "idempotency_key"), name="content_personal_receipt_unique"
            ),
        ),
    ]
