# Generated by Django 5.2.17 on 2026-10-08 14:26

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_personal_sheet'),
        ('files', '0006_practice_sets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practice_sets', to='content.catalogsubject')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PracticeSlide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('answer', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('managed_file', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='practice_slide', to='files.managedfile')),
                ('practice_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='content.practiceset')),
            ],
            options={
                'ordering': ('position', 'created_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='practiceset',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('subject'), name='content_practice_set_title_unique'),
        ),
        migrations.AddIndex(
            model_name='practiceslide',
            index=models.Index(fields=['practice_set', 'position'], name='content_practice_slide_pos'),
        ),
    ]
