# Generated by Django 5.2.17 on 2026-10-08 16:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_practice_sets'),
        ('files', '0006_practice_sets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSlideProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('miss_count', models.PositiveIntegerField(default=0)),
                ('streak', models.PositiveSmallIntegerField(default=0)),
                ('last_correct', models.BooleanField(default=False)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('hint_pending', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='practiceslide',
            name='hotspot_shape',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='practiceslide',
            name='hotspot_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practiceslide',
            name='hotspot_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='practiceslide',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hotspot_shape', ''), ('hotspot_x__isnull', True), ('hotspot_y__isnull', True)), models.Q(('hotspot_shape__in', ('circle', 'arrow')), ('hotspot_x__gte', 0), ('hotspot_x__lte', 1), ('hotspot_y__gte', 0), ('hotspot_y__lte', 1)), _connector='OR'), name='content_practice_slide_hotspot_valid'),
        ),
        migrations.AddField(
            model_name='practiceslideprogress',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='content.practiceslide'),
        ),
        migrations.AddField(
            model_name='practiceslideprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='practiceslideprogress',
            index=models.Index(fields=['user', 'due_at'], name='content_practice_prog_due'),
        ),
        migrations.AddConstraint(
            model_name='practiceslideprogress',
            constraint=models.UniqueConstraint(fields=('user', 'slide'), name='content_practice_progress_once'),
        ),
    ]
