from django.urls import path

from .admin_views import (
    AdminSheetActionView,
    AdminSheetActiveStudyPreviewView,
    AdminSheetActiveStudyQuestionsView,
    AdminSheetActiveStudyView,
    AdminSheetAllQuestionsValidateView,
    AdminSheetAllQuestionsView,
    AdminSheetDetailView,
    AdminSheetLockinPdfView,
    AdminSheetPdfView,
    AdminSheetReorderView,
    AdminSheetSummaryPdfView,
    AdminSubjectListView,
    AdminSubjectSheetListView,
)
from .personal_sheet_views import (
    PersonalSheetCollectionView,
    PersonalSheetDeleteView,
    PersonalSheetDetailView,
    PersonalSheetWorkspaceView,
)
from .practice_views import (
    AdminPracticeAnswersView,
    AdminPracticeDuplicateView,
    AdminPracticeReorderView,
    AdminPracticeSetDetailView,
    AdminPracticeSetListView,
    AdminPracticeSlideCollectionView,
    AdminPracticeSlideDetailView,
    AdminPracticeSlideImageView,
    AdminPracticeSlideMoveView,
    PracticeCheckView,
    PracticeDirectoryView,
    PracticeHintView,
    PracticeSetView,
)
from .views import (
    ArchiveLearningObjectView,
    CatalogDocumentResolveView,
    CatalogMaterialListView,
    CatalogQuestionMaterialListView,
    CatalogSheetQuestionAnswerView,
    CatalogSheetQuestionListView,
    CatalogSheetQuestionRetryView,
    CatalogWorkspaceView,
    ManagementLearningObjectDetailView,
    ManagementLearningObjectListView,
    PublicLearningObjectDetailView,
    PublicLearningObjectListView,
    PublishLearningObjectView,
    RejectLearningObjectView,
    SubmitLearningObjectView,
    TransferLearningObjectView,
)

app_name = "content"

urlpatterns = [
    # Keep the structural UUID route before the two-slug alias resolver: UUIDs
    # are valid slugs, so the broader pattern would otherwise shadow workspace
    # GET/PATCH requests and return 404/405 before authorization is evaluated.
    path("catalog/documents/<uuid:document_id>/workspace", CatalogWorkspaceView.as_view()),
    path("catalog/materials", CatalogMaterialListView.as_view(), name="catalog-materials"),
    path(
        "catalog/materials/<slug:material_slug>/personal-sheets",
        PersonalSheetCollectionView.as_view(),
        name="personal-sheets",
    ),
    path(
        "personal-sheets/delete",
        PersonalSheetDeleteView.as_view(),
        name="personal-sheets-delete",
    ),
    path(
        "personal-sheets/<uuid:sheet_id>",
        PersonalSheetDetailView.as_view(),
        name="personal-sheet-detail",
    ),
    path(
        "personal-sheets/<uuid:sheet_id>/workspace",
        PersonalSheetWorkspaceView.as_view(),
        name="personal-sheet-workspace",
    ),
    path(
        "catalog/questions",
        CatalogQuestionMaterialListView.as_view(),
        name="catalog-questions",
    ),
    path(
        "catalog/sheets/<uuid:sheet_id>/questions",
        CatalogSheetQuestionListView.as_view(),
        name="catalog-sheet-questions",
    ),
    path(
        "catalog/sheets/<uuid:sheet_id>/questions/<uuid:question_id>/answer",
        CatalogSheetQuestionAnswerView.as_view(),
        name="catalog-sheet-question-answer",
    ),
    path(
        "catalog/sheets/<uuid:sheet_id>/questions/<uuid:question_id>/retry",
        CatalogSheetQuestionRetryView.as_view(),
        name="catalog-sheet-question-retry",
    ),
    path(
        "catalog/documents/<slug:material_slug>/<slug:sheet_slug>",
        CatalogDocumentResolveView.as_view(),
    ),
    path("catalog/practice", PracticeDirectoryView.as_view(), name="practice-directory"),
    path("catalog/practice/<uuid:set_id>", PracticeSetView.as_view(), name="practice-set"),
    path(
        "catalog/practice/<uuid:set_id>/slides/<uuid:slide_id>/check",
        PracticeCheckView.as_view(),
        name="practice-check",
    ),
    path(
        "catalog/practice/<uuid:set_id>/slides/<uuid:slide_id>/hint",
        PracticeHintView.as_view(),
        name="practice-hint",
    ),
    path(
        "operations/admin/content/subjects/<uuid:subject_id>/practice",
        AdminPracticeSetListView.as_view(),
        name="admin-practice-sets",
    ),
    path(
        "operations/admin/content/practice/<uuid:set_id>",
        AdminPracticeSetDetailView.as_view(),
        name="admin-practice-set",
    ),
    path(
        "operations/admin/content/practice/<uuid:set_id>/slides",
        AdminPracticeSlideCollectionView.as_view(),
        name="admin-practice-slides",
    ),
    path(
        "operations/admin/content/practice/<uuid:set_id>/slides/<uuid:slide_id>",
        AdminPracticeSlideDetailView.as_view(),
        name="admin-practice-slide",
    ),
    path(
        "operations/admin/content/practice/<uuid:set_id>/reorder",
        AdminPracticeReorderView.as_view(),
        name="admin-practice-reorder",
    ),
    path(
        "operations/admin/content/practice/<uuid:set_id>/answers",
        AdminPracticeAnswersView.as_view(),
        name="admin-practice-answers",
    ),
    path(
        "operations/admin/content/practice/<uuid:set_id>/duplicate",
        AdminPracticeDuplicateView.as_view(),
        name="admin-practice-duplicate",
    ),
    path(
        "operations/admin/content/practice/<uuid:set_id>/slides/<uuid:slide_id>/move",
        AdminPracticeSlideMoveView.as_view(),
        name="admin-practice-slide-move",
    ),
    path(
        "operations/admin/content/practice/<uuid:set_id>/slides/<uuid:slide_id>/image",
        AdminPracticeSlideImageView.as_view(),
        name="admin-practice-slide-image",
    ),
    path(
        "operations/admin/content/subjects",
        AdminSubjectListView.as_view(),
        name="admin-subjects",
    ),
    path(
        "operations/admin/content/subjects/<uuid:subject_id>/sheets",
        AdminSubjectSheetListView.as_view(),
        name="admin-subject-sheets",
    ),
    path(
        "operations/admin/content/sheets/<uuid:sheet_id>",
        AdminSheetDetailView.as_view(),
        name="admin-sheet-detail",
    ),
    path(
        "operations/admin/content/sheets/<uuid:sheet_id>/actions",
        AdminSheetActionView.as_view(),
        name="admin-sheet-action",
    ),
    path(
        "operations/admin/content/sheets/<uuid:sheet_id>/pdf",
        AdminSheetPdfView.as_view(),
        name="admin-sheet-pdf",
    ),
    path(
        "operations/admin/content/sheets/<uuid:sheet_id>/summary-pdf",
        AdminSheetSummaryPdfView.as_view(),
        name="admin-sheet-summary-pdf",
    ),
    path(
        "operations/admin/content/sheets/<uuid:sheet_id>/reorder",
        AdminSheetReorderView.as_view(),
        name="admin-sheet-reorder",
    ),
    path(
        "operations/admin/content/sheets/<uuid:sheet_id>/lockin-pdf",
        AdminSheetLockinPdfView.as_view(),
        name="admin-sheet-lockin-pdf",
    ),
    path(
        "operations/admin/content/sheets/<uuid:sheet_id>/active-study",
        AdminSheetActiveStudyView.as_view(),
        name="admin-sheet-active-study",
    ),
    path(
        "operations/admin/content/sheets/<uuid:sheet_id>/active-study/preview",
        AdminSheetActiveStudyPreviewView.as_view(),
        name="admin-sheet-active-study-preview",
    ),
    path(
        "operations/admin/content/sheets/<uuid:sheet_id>/active-study/questions/<str:difficulty>",
        AdminSheetActiveStudyQuestionsView.as_view(),
        name="admin-sheet-active-study-questions",
    ),
    path(
        "operations/admin/content/sheets/<uuid:sheet_id>/all-questions",
        AdminSheetAllQuestionsView.as_view(),
        name="admin-sheet-all-questions",
    ),
    path(
        "operations/admin/content/sheets/<uuid:sheet_id>/all-questions/validate",
        AdminSheetAllQuestionsValidateView.as_view(),
        name="admin-sheet-all-questions-validate",
    ),
    path("learning-objects", PublicLearningObjectListView.as_view(), name="public-list"),
    path(
        "learning-objects/<uuid:learning_object_id>",
        PublicLearningObjectDetailView.as_view(),
        name="public-detail",
    ),
    path(
        "management/content",
        ManagementLearningObjectListView.as_view(),
        name="management-list",
    ),
    path(
        "management/content/<uuid:learning_object_id>",
        ManagementLearningObjectDetailView.as_view(),
        name="management-detail",
    ),
    path(
        "management/content/<uuid:learning_object_id>/submit",
        SubmitLearningObjectView.as_view(),
        name="submit",
    ),
    path(
        "management/content/<uuid:learning_object_id>/publish",
        PublishLearningObjectView.as_view(),
        name="publish",
    ),
    path(
        "management/content/<uuid:learning_object_id>/reject",
        RejectLearningObjectView.as_view(),
        name="reject",
    ),
    path(
        "management/content/<uuid:learning_object_id>/archive",
        ArchiveLearningObjectView.as_view(),
        name="archive",
    ),
    path(
        "management/content/<uuid:learning_object_id>/transfer",
        TransferLearningObjectView.as_view(),
        name="transfer",
    ),
]
