# Generated by Django 5.2.16 on 2026-07-15 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_kind', models.CharField(max_length=32)),
                ('resource_id', models.UUIDField()),
                ('content_type', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(max_length=220)),
                ('normalized_title', models.CharField(db_index=True, max_length=220)),
                ('summary', models.TextField(blank=True)),
                ('language', models.CharField(default='und', max_length=12)),
                ('academic_path', models.CharField(db_index=True, max_length=2048)),
                ('is_discoverable', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title', 'resource_kind', 'resource_id'),
                'indexes': [models.Index(fields=['is_discoverable', 'resource_kind', 'content_type'], name='discovery_filter_idx'), models.Index(fields=['is_discoverable', '-published_at', 'id'], name='discovery_recent_idx')],
                'constraints': [models.UniqueConstraint(fields=('resource_kind', 'resource_id'), name='discovery_resource_unique')],
            },
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=80)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='discovery.searchentry')),
            ],
            options={
                'indexes': [models.Index(fields=['term', 'entry'], name='discovery_term_entry_idx')],
                'constraints': [models.UniqueConstraint(fields=('entry', 'term'), name='discovery_term_unique')],
            },
        ),
    ]
