# Generated by Django 5.2.16 on 2026-07-18 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=120)),
                ('domain', models.CharField(max_length=60)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=80)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('related_entities', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_audit_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['-occurred_at', '-id'], name='audit_time_id_idx'), models.Index(fields=['domain', '-occurred_at'], name='audit_domain_time_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_target_idx'), models.Index(fields=['actor', '-occurred_at'], name='audit_actor_time_idx')],
            },
        ),
    ]
