# Generated by Django 5.2.16 on 2026-07-18 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('category', models.CharField(max_length=32)),
                ('icon_key', models.CharField(max_length=48)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('category', 'code'),
            },
        ),
        migrations.CreateModel(
            name='AchievementVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField()),
                ('title_en', models.CharField(max_length=120)),
                ('title_ar', models.CharField(max_length=120)),
                ('description_en', models.CharField(max_length=240)),
                ('description_ar', models.CharField(max_length=240)),
                ('criteria', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='achievements.achievementdefinition')),
            ],
            options={
                'ordering': ('definition', '-version'),
            },
        ),
        migrations.CreateModel(
            name='AchievementProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.PositiveBigIntegerField(default=0)),
                ('target_value', models.PositiveBigIntegerField()),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievementdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_progress', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='achievements.achievementversion')),
            ],
        ),
        migrations.AddField(
            model_name='achievementdefinition',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_definitions', to='achievements.achievementversion'),
        ),
        migrations.CreateModel(
            name='EarnedAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_snapshot', models.JSONField(default=dict)),
                ('earned_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='achievements.achievementdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earned_achievements', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='achievements.achievementversion')),
            ],
            options={
                'ordering': ('-earned_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AchievementEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=180)),
                ('evidence_type', models.CharField(max_length=80)),
                ('source_object_id', models.UUIDField(blank=True, null=True)),
                ('value', models.PositiveIntegerField(default=1)),
                ('occurred_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievement_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'evidence_type'], name='achievement_user_type_idx'), models.Index(fields=['evidence_type', 'occurred_at'], name='achievement_type_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'source_key'), name='achievement_evidence_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='achievementversion',
            constraint=models.UniqueConstraint(fields=('definition', 'version'), name='achievement_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='achievementprogress',
            constraint=models.UniqueConstraint(fields=('user', 'definition'), name='achievement_progress_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='achievementprogress',
            constraint=models.CheckConstraint(condition=models.Q(('current_value__gte', 0)), name='achievement_progress_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='earnedachievement',
            index=models.Index(fields=['user', '-earned_at'], name='achievement_user_earned_idx'),
        ),
        migrations.AddIndex(
            model_name='earnedachievement',
            index=models.Index(fields=['definition', '-earned_at'], name='achievement_def_earned_idx'),
        ),
        migrations.AddConstraint(
            model_name='earnedachievement',
            constraint=models.UniqueConstraint(fields=('user', 'definition'), name='achievement_earned_user_unique'),
        ),
    ]
