# Generated by Django 5.2.17 on 2026-09-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0002_paymentstatuscorrection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationcampaigndelivery',
            name='email_status',
            field=models.CharField(default='not_requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationcampaigndelivery',
            name='in_app_status',
            field=models.CharField(default='not_requested', max_length=20),
        ),
    ]
