# Generated by Django 5.2.17 on 2026-10-07 20:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('feature', 'Feature'), ('improvement', 'Improvement'), ('problem', 'Problem'), ('general', 'General')], default='feature', max_length=16)),
                ('message', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('new', 'New'), ('planned', 'Planned'), ('done', 'Done'), ('declined', 'Declined')], default='new', max_length=12)),
                ('admin_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'id'),
                'indexes': [models.Index(fields=['status', '-created_at'], name='feedback_status_idx'), models.Index(fields=['user', '-created_at'], name='feedback_user_idx')],
            },
        ),
    ]
