# Generated by Django 5.2.16 on 2026-07-18 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationEntry',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value_type', models.CharField(choices=[('integer', 'Integer'), ('boolean', 'Boolean'), ('string', 'String')], max_length=12)),
                ('value', models.JSONField()),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuration_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
    ]
