# Generated by Django 5.2.16 on 2026-07-18 03:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('individual', 'Individual'), ('family', 'Family (future)'), ('organization', 'Organization (future)'), ('institution', 'Institution (future)')], max_length=16)),
                ('display_name', models.CharField(max_length=160)),
                ('external_subject_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('trialing', 'Trial'), ('active', 'Active'), ('grace', 'Grace period'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended'), ('refunded', 'Refunded')], max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_started_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_ends_at', models.DateTimeField(blank=True, null=True)),
                ('grace_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancellation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status_reason', models.CharField(blank=True, max_length=80)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='product_catalog.planversion')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionaccount')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pending payment'), ('trialing', 'Trial'), ('active', 'Active'), ('grace', 'Grace period'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended'), ('refunded', 'Refunded')], max_length=12)),
                ('to_status', models.CharField(choices=[('pending', 'Pending payment'), ('trialing', 'Trial'), ('active', 'Active'), ('grace', 'Grace period'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended'), ('refunded', 'Refunded')], max_length=12)),
                ('source', models.CharField(choices=[('system', 'System'), ('user', 'User request'), ('admin', 'Administrator'), ('provider', 'Verified provider event'), ('reconciliation', 'Reconciliation')], max_length=16)),
                ('reason_code', models.CharField(max_length=80)),
                ('source_reference', models.CharField(blank=True, max_length=160)),
                ('idempotency_key', models.CharField(blank=True, max_length=180)),
                ('effective_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_transitions_made', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ('effective_at', 'created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='subscriptionaccount',
            index=models.Index(fields=['kind', 'status'], name='subscription_account_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'individual'), ('primary_user__isnull', False)), fields=('primary_user',), name='subscription_individual_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'individual'), _negated=True), ('primary_user__isnull', False), _connector='OR'), name='subscription_individual_has_user'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['account', 'status', '-created_at'], name='subscription_account_state_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'current_period_ends_at'], name='subscription_period_due_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'trial_ends_at'], name='subscription_trial_due_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'grace_ends_at'], name='subscription_grace_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('trialing', 'active', 'grace', 'suspended'))), fields=('account',), name='subscription_one_live_per_account'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('account',), name='subscription_one_pending_per_account'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('trial_ends_at__isnull', True), ('trial_started_at__isnull', True), ('trial_ends_at__gt', models.F('trial_started_at')), _connector='OR'), name='subscription_trial_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('current_period_ends_at__isnull', True), ('current_period_started_at__isnull', True), ('current_period_ends_at__gt', models.F('current_period_started_at')), _connector='OR'), name='subscription_period_window_valid'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontransition',
            index=models.Index(fields=['subscription', '-effective_at'], name='sub_transition_time_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontransition',
            index=models.Index(fields=['source', 'source_reference'], name='subscription_source_ref_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptiontransition',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('subscription', 'idempotency_key'), name='subscription_transition_idempotent'),
        ),
    ]
