# Generated by Django 5.2.16 on 2026-07-17 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0002_remove_creatorscope_edu_scope_has_capability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('published', 'Published'), ('rejected', 'Rejected'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('review_note', models.TextField(blank=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuestionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('question_type', models.CharField(choices=[('single_choice', 'Single choice'), ('true_false', 'True or false'), ('completion_choice', 'Completion from choices')], max_length=24)),
                ('prompt', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=12)),
                ('language', models.CharField(default='en', max_length=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_versions', to='education.educationnode')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_question_versions', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='questions.question')),
            ],
            options={
                'ordering': ('-version_number',),
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('position', models.PositiveSmallIntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='questions.questionversion')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for', to='questions.questionversion'),
        ),
        migrations.AddField(
            model_name='question',
            name='published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_for', to='questions.questionversion'),
        ),
        migrations.AddIndex(
            model_name='questionversion',
            index=models.Index(fields=['academic_node', 'difficulty', 'question_type'], name='question_scope_filter_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.UniqueConstraint(fields=('question', 'version_number'), name='question_version_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('version', 'position'), name='question_option_position_unique'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['owner', 'workflow_status', '-updated_at'], name='question_owner_flow_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['workflow_status', '-published_at'], name='question_publication_idx'),
        ),
    ]
