# Generated by Django 5.2.16 on 2026-08-28 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_source_learning_objects(apps, schema_editor):
    QuestionVersion = apps.get_model('questions', 'QuestionVersion')
    LearningObjectVersion = apps.get_model('content', 'LearningObjectVersion')
    for version in QuestionVersion.objects.filter(source_learning_object__isnull=True).iterator():
        candidates = list(
            LearningObjectVersion.objects.filter(academic_node_id=version.academic_node_id)
            .values_list('learning_object_id', flat=True)
            .distinct()[:2]
        )
        if len(candidates) == 1:
            version.source_learning_object_id = candidates[0]
            version.save(update_fields=('source_learning_object',))


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_learningobject_position_and_more'),
        ('education', '0005_restore_legacy_dentistry_and_preparatory_cohorts'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Imported as draft'), ('published', 'Imported and published'), ('undone', 'Undone')], max_length=16)),
                ('question_count', models.PositiveIntegerField()),
                ('type_counts', models.JSONField(default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='questionversion',
            name='source_learning_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_versions', to='content.learningobject'),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='source_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='topic',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='questionversion',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single choice'), ('true_false', 'True or false'), ('completion_choice', 'Completion from choices'), ('multiple_select', 'Multiple select')], max_length=24),
        ),
        migrations.AddIndex(
            model_name='questionversion',
            index=models.Index(fields=['source_learning_object', 'question_type'], name='question_sheet_type_idx'),
        ),
        migrations.AddField(
            model_name='questionimportbatch',
            name='academic_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_import_batches', to='education.educationnode'),
        ),
        migrations.AddField(
            model_name='questionimportbatch',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionimportbatch',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_import_batches', to='content.learningobject'),
        ),
        migrations.AddField(
            model_name='questionimportbatch',
            name='undone_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='undone_question_import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questions.questionimportbatch'),
        ),
        migrations.RunPython(backfill_source_learning_objects, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='questionimportbatch',
            index=models.Index(fields=['sheet', '-created_at'], name='question_import_sheet_idx'),
        ),
        migrations.AddIndex(
            model_name='questionimportbatch',
            index=models.Index(fields=['status', '-created_at'], name='question_import_status_idx'),
        ),
    ]
