# Generated by Django 5.2.17 on 2026-09-18 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_questionimportbatch_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("selected_option_ids", models.JSONField(default=list)),
                ("is_correct", models.BooleanField()),
                ("xp_awarded", models.PositiveSmallIntegerField(default=0)),
                ("answered_at", models.DateTimeField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="questions.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="questions.questionversion",
                    ),
                ),
            ],
            options={
                "ordering": ("-answered_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "question"), name="question_answer_user_question_unique"
                    )
                ],
            },
        ),
    ]
