# Generated by Django 5.2.16 on 2026-07-17 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('discussion', 'Discussion'), ('comment', 'Comment'), ('question', 'Question'), ('answer', 'Answer'), ('explanation', 'Explanation'), ('learning_object', 'Learning object')], max_length=24)),
                ('target_id', models.UUIDField()),
                ('target_version_id', models.UUIDField(blank=True, null=True)),
                ('target_author_id', models.UUIDField(blank=True, null=True)),
                ('target_label', models.CharField(max_length=220)),
                ('context_type', models.CharField(blank=True, max_length=24)),
                ('context_id', models.UUIDField(blank=True, null=True)),
                ('private_space_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Abuse or harassment'), ('incorrect_question', 'Incorrect question'), ('incorrect_answer', 'Incorrect answer'), ('incorrect_explanation', 'Incorrect explanation'), ('duplicate', 'Duplicate'), ('other', 'Other')], max_length=28)),
                ('description', models.TextField()),
                ('evidence_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('triaged', 'Triaged'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], default='open', max_length=16)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('important', 'Important'), ('urgent', 'Urgent')], default='routine', max_length=12)),
                ('resolution_notes', models.TextField(blank=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('client_request_id', models.UUIDField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_moderation_reports', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicates', to='moderation.report')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ModerationAuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('report_created', 'Report created'), ('triaged', 'Triaged'), ('assigned', 'Assigned'), ('started', 'Started'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('marked_duplicate', 'Marked duplicate'), ('content_removed', 'Content removed'), ('content_restored', 'Content restored'), ('discussion_locked', 'Discussion locked'), ('discussion_unlocked', 'Discussion unlocked')], max_length=24)),
                ('target_type', models.CharField(max_length=24)),
                ('target_id', models.UUIDField()),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='moderation.report')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ModerationRateBucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('window_started_at', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_rate_buckets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['window_started_at'], name='moderation_rate_cleanup_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'window_started_at'), name='moderation_rate_bucket_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'priority', '-created_at'], name='moderation_queue_status_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['assigned_to', 'status', '-updated_at'], name='moderation_assignment_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['target_type', 'target_id', 'status'], name='moderation_target_status_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter', '-created_at'], name='moderation_reporter_time_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['private_space_id', 'status', '-created_at'], name='moderation_private_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('reporter', 'client_request_id'), name='moderation_report_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('status__in', ('open', 'triaged', 'in_progress'))), models.Q(('resolved_at__isnull', False), ('status__in', ('resolved', 'rejected', 'duplicate'))), _connector='OR'), name='moderation_report_resolution_consistent'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('duplicate_of_id')), _negated=True), name='moderation_report_not_own_duplicate'),
        ),
        migrations.AddIndex(
            model_name='moderationauditentry',
            index=models.Index(fields=['actor', '-created_at'], name='moderation_actor_audit_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationauditentry',
            index=models.Index(fields=['target_type', 'target_id', '-created_at'], name='moderation_target_audit_idx'),
        ),
    ]
