# Generated by Django 5.2.16 on 2026-07-15 11:16

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('registered', 'Registered'), ('email_verified', 'Email verified'), ('email_changed', 'Email changed'), ('password_changed', 'Password changed'), ('password_reset', 'Password reset'), ('login_succeeded', 'Login succeeded'), ('logout', 'Logout'), ('role_changed', 'Role changed')], max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AccountSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('device_label', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ('-last_seen_at',),
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64)),
                ('attempted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('email_verification', 'Email verification'), ('password_reset', 'Password reset'), ('email_change', 'Email change')], max_length=24)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='policy_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='policy_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_user_email_ci_unique'),
        ),
        migrations.AddField(
            model_name='accountsecurityevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_security_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountsecurityevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['key_hash', 'attempted_at'], name='accounts_lo_key_has_320a2e_idx'),
        ),
        migrations.AddField(
            model_name='onetimetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accountsession',
            index=models.Index(fields=['user', 'expires_at'], name='accounts_ac_user_id_d10d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='onetimetoken',
            index=models.Index(fields=['user', 'kind', 'used_at'], name='accounts_on_user_id_d777e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='onetimetoken',
            constraint=models.CheckConstraint(condition=models.Q(('used_at__isnull', True), ('used_at__gte', models.F('created_at')), _connector='OR'), name='accounts_token_used_after_created'),
        ),
    ]
