# Generated by Django 5.2.16 on 2026-07-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_generalize_auth_attempt_throttling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsecurityevent',
            name='event_type',
            field=models.CharField(choices=[('registered', 'Registered'), ('email_verified', 'Email verified'), ('email_changed', 'Email changed'), ('password_changed', 'Password changed'), ('password_reset', 'Password reset'), ('login_succeeded', 'Login succeeded'), ('logout', 'Logout'), ('role_changed', 'Role changed'), ('status_changed', 'Status changed')], max_length=24),
        ),
    ]
