# Generated by Django 5.2.16 on 2026-08-31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_user_avatar_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimetoken",
            name="kind",
            field=models.CharField(
                choices=[
                    ("email_verification", "Email verification"),
                    ("password_reset", "Password reset"),
                    ("email_change", "Email change"),
                    ("account_deletion", "Account deletion"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="accountsecurityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("registered", "Registered"),
                    ("email_verified", "Email verified"),
                    ("email_changed", "Email changed"),
                    ("password_changed", "Password changed"),
                    ("password_reset", "Password reset"),
                    ("login_succeeded", "Login succeeded"),
                    ("social_identity_linked", "Social identity linked"),
                    ("social_login_succeeded", "Social login succeeded"),
                    ("logout", "Logout"),
                    ("role_changed", "Role changed"),
                    ("status_changed", "Status changed"),
                    ("deletion_requested", "Deletion requested"),
                    ("deletion_confirmed", "Deletion confirmed"),
                    ("deletion_cancelled", "Deletion cancelled"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="AccountDeletionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_confirmation", "Pending confirmation"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_confirmation",
                        max_length=24,
                    ),
                ),
                ("policy_version", models.CharField(blank=True, max_length=80)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmation_token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_deletion_request",
                        to="accounts.onetimetoken",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-requested_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["status", "requested_at"], name="account_delete_state_idx"
                    ),
                    models.Index(
                        fields=["user", "status"], name="account_delete_user_idx"
                    ),
                ],
            },
        ),
    ]
