# Generated by Django 5.2.16 on 2026-07-17 17:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0002_remove_creatorscope_edu_scope_has_capability_and_more'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('submitted', 'Submitted'), ('expired', 'Expired and submitted')], default='active', max_length=12)),
                ('start_idempotency_key', models.UUIDField()),
                ('requested_question_count', models.PositiveSmallIntegerField()),
                ('review_only', models.BooleanField(default=False)),
                ('server_revision', models.PositiveBigIntegerField(default=1)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('prompt', models.TextField()),
                ('question_type', models.CharField(max_length=24)),
                ('difficulty', models.CharField(max_length=12)),
                ('language', models.CharField(max_length=12)),
                ('explanation', models.TextField(blank=True)),
                ('option_snapshot', models.JSONField(default=list)),
                ('correct_option_ids', models.JSONField(default=list)),
                ('max_points', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.attempt')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_snapshots', to='questions.questionversion')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_option_ids', models.JSONField(default=list)),
                ('client_revision', models.PositiveBigIntegerField()),
                ('server_revision', models.PositiveBigIntegerField()),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('attempt_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='assessments.attemptquestion')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_points', models.DecimalField(decimal_places=2, max_digits=8)),
                ('maximum_points', models.DecimalField(decimal_places=2, max_digits=8)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passed', models.BooleanField()),
                ('answered_count', models.PositiveSmallIntegerField()),
                ('unanswered_count', models.PositiveSmallIntegerField()),
                ('ranking_eligible', models.BooleanField(default=False)),
                ('achievement_eligible', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='assessments.attempt')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptSubmissionReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_receipts', to='assessments.attempt')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='assessments.attemptresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionIssueReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('answer_key', 'Answer key'), ('ambiguous', 'Ambiguous wording'), ('outdated', 'Outdated content'), ('typo', 'Typographical error'), ('other', 'Other')], max_length=16)),
                ('details', models.TextField()),
                ('evidence_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_reports', to='assessments.attemptquestion')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_issue_reports', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_reports', to='assessments.attemptresult')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('published', 'Published'), ('rejected', 'Rejected'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('review_note', models.TextField(blank=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='assessments.quiz'),
        ),
        migrations.CreateModel(
            name='QuizVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=220)),
                ('instructions', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('quiz', 'Quiz'), ('practice', 'Practice'), ('mastery', 'Mastery test')], max_length=12)),
                ('selection_mode', models.CharField(choices=[('fixed', 'Fixed questions'), ('pool', 'Question pool')], max_length=12)),
                ('question_count', models.PositiveSmallIntegerField()),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('randomize_questions', models.BooleanField(default=True)),
                ('randomize_options', models.BooleanField(default=True)),
                ('result_release', models.CharField(choices=[('immediate', 'Immediately'), ('after_close', 'After availability closes')], default='immediate', max_length=16)),
                ('pass_percent', models.DecimalField(decimal_places=2, default=60, max_digits=5)),
                ('ranking_eligible', models.BooleanField(default=False)),
                ('achievement_eligible', models.BooleanField(default=False)),
                ('focus_required', models.BooleanField(default=False)),
                ('allowed_difficulties', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(default='en', max_length=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_versions', to='education.educationnode')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_quiz_versions', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='assessments.quiz')),
            ],
            options={
                'ordering': ('-version_number',),
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for', to='assessments.quizversion'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_for', to='assessments.quizversion'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='quiz_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='assessments.quizversion'),
        ),
        migrations.CreateModel(
            name='QuizVersionQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_links', to='questions.questionversion')),
                ('quiz_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_links', to='assessments.quizversion')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AttemptActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_event_id', models.UUIDField()),
                ('activity_type', models.CharField(choices=[('workspace_entered', 'Workspace entered'), ('page_hidden', 'Page hidden'), ('page_visible', 'Page visible'), ('connection_lost', 'Connection lost'), ('connection_restored', 'Connection restored'), ('workspace_exited', 'Workspace exited')], max_length=24)),
                ('client_occurred_at', models.DateTimeField(blank=True, null=True)),
                ('server_received_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='assessments.attempt')),
            ],
            options={
                'ordering': ('server_received_at', 'id'),
                'indexes': [models.Index(fields=['attempt', 'server_received_at'], name='attempt_activity_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'client_event_id'), name='attempt_activity_event_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='attemptquestion',
            index=models.Index(fields=['attempt', 'position'], name='attempt_question_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'position'), name='attempt_question_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'question_version'), name='attempt_question_version_unique'),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['attempt_question', 'saved_at'], name='answer_saved_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptresult',
            index=models.Index(fields=['attempt', 'submitted_at'], name='result_attempt_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='attemptsubmissionreceipt',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='submission_user_key_unique'),
        ),
        migrations.AddIndex(
            model_name='questionissuereport',
            index=models.Index(fields=['status', '-created_at'], name='question_report_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionissuereport',
            constraint=models.UniqueConstraint(fields=('reporter', 'result', 'attempt_question'), name='question_report_once_unique'),
        ),
        migrations.AddIndex(
            model_name='quizversion',
            index=models.Index(fields=['academic_node', 'mode', '-created_at'], name='quiz_scope_mode_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizversion',
            constraint=models.UniqueConstraint(fields=('quiz', 'version_number'), name='quiz_version_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='quizversion',
            constraint=models.CheckConstraint(condition=models.Q(('question_count__gte', 1), ('question_count__lte', 100)), name='quiz_question_count_valid'),
        ),
        migrations.AddConstraint(
            model_name='quizversion',
            constraint=models.CheckConstraint(condition=models.Q(('pass_percent__gte', 0), ('pass_percent__lte', 100)), name='quiz_pass_percent_valid'),
        ),
        migrations.AddConstraint(
            model_name='quizversion',
            constraint=models.CheckConstraint(condition=models.Q(('available_from__isnull', True), ('available_until__isnull', True), ('available_until__gt', models.F('available_from')), _connector='OR'), name='quiz_availability_order'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['owner', 'workflow_status', '-updated_at'], name='quiz_owner_flow_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['workflow_status', '-published_at'], name='quiz_publication_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'status', '-started_at'], name='attempt_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['quiz', 'user', '-started_at'], name='attempt_quiz_user_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['status', 'deadline_at'], name='attempt_deadline_idx'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('user', 'start_idempotency_key'), name='attempt_start_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(condition=models.Q(('deadline_at__isnull', True), ('deadline_at__gt', models.F('started_at')), _connector='OR'), name='attempt_deadline_valid'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'active')), models.Q(('completed_at__isnull', False), ('status__in', ('submitted', 'expired'))), _connector='OR'), name='attempt_completion_consistent'),
        ),
        migrations.AddConstraint(
            model_name='quizversionquestion',
            constraint=models.UniqueConstraint(fields=('quiz_version', 'position'), name='quiz_question_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='quizversionquestion',
            constraint=models.UniqueConstraint(fields=('quiz_version', 'question_version'), name='quiz_question_version_unique'),
        ),
    ]
