# Generated by Django 5.2.16 on 2026-07-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionissuereport',
            name='category',
            field=models.CharField(choices=[('answer_key', 'Answer key'), ('ambiguous', 'Ambiguous wording'), ('outdated', 'Outdated content'), ('typo', 'Typographical error'), ('explanation', 'Incorrect explanation'), ('other', 'Other')], max_length=16),
        ),
    ]
