import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { DIFFICULTIES, managementApi, QUESTION_TYPES, QUIZ_MODES, QUIZ_SELECTION_MODES, RESULT_RELEASES } from "../api/management.js";
import { Icon } from "../lib/icons.jsx";
import { useAsyncData } from "../hooks/useAsyncData.js";
import { EmptyState, ErrorPanel, LoadingPanel, Page } from "../components/ui/index.jsx";
import { CreatorNotice, CreatorTabs, FieldError, humanize, isoDateTime, LifecycleActions, localDateTime, NodePicker, QuestionOptionsEditor, QuizQuestionPicker, WorkflowStatus } from "../components/creator/index.jsx";

async function allNodes() {
  const nodes = []; let page = 1; let hasNext = true;
  while (hasNext) { const result = await managementApi.listNodes({ page, pageSize: 100 }); nodes.push(...result.results); hasNext = result.hasNext; page += 1; }
  return nodes;
}

async function allQuestions() {
  const questions = []; let page = 1; let hasNext = true;
  while (hasNext) { const result = await managementApi.listQuestions({ page, pageSize: 100 }); questions.push(...result.results); hasNext = result.hasNext; page += 1; }
  return questions;
}

function questionState(item) {
  const version = item?.current_version;
  return { academicNodeId: version?.academic_node_id || "", questionType: version?.question_type || "single_choice", prompt: version?.prompt || "", explanation: version?.explanation || "", difficulty: version?.difficulty || "medium", language: version?.language || "en", options: Array.isArray(version?.options) && version.options.length ? version.options.map((option) => ({ text: option.text || "", isCorrect: option.is_correct === true })) : [{ text: "", isCorrect: true }, { text: "", isCorrect: false }] };
}

function quizState(item) {
  const version = item?.current_version;
  return { academicNodeId: version?.academic_node_id || "", title: version?.title || "", instructions: version?.instructions || "", mode: version?.mode || "quiz", selectionMode: version?.selection_mode || "fixed", questionCount: version?.question_count ?? 1, questionIds: Array.isArray(version?.question_links) ? version.question_links.map((link) => link.question_id).filter(Boolean) : [], durationSeconds: version?.duration_seconds ?? "", maximumAttempts: version?.maximum_attempts ?? 0, availableFrom: localDateTime(version?.available_from), availableUntil: localDateTime(version?.available_until), randomizeQuestions: version?.randomize_questions !== false, randomizeOptions: version?.randomize_options !== false, resultRelease: version?.result_release || "immediate", passPercent: version?.pass_percent ?? "60.00", rankingEligible: version?.ranking_eligible === true, achievementEligible: version?.achievement_eligible === true, focusRequired: version?.focus_required === true, allowedDifficulties: Array.isArray(version?.allowed_difficulties) ? version.allowed_difficulties : [], language: version?.language || "en" };
}

function usePagedManagement(loader, filters) {
  const data = useAsyncData(() => loader({ page: 1, pageSize: 25, ...filters }), Object.values(filters));
  const [items, setItems] = useState([]); const [nextPage, setNextPage] = useState(2); const [hasNext, setHasNext] = useState(false); const [loadingMore, setLoadingMore] = useState(false); const [error, setError] = useState(null);
  useEffect(() => { if (data.data) { setItems(data.data.results); setHasNext(data.data.hasNext); setNextPage(2); setError(null); } }, [data.data]);
  async function loadMore() { if (!hasNext || loadingMore) return; setLoadingMore(true); setError(null); try { const result = await loader({ page: nextPage, pageSize: 25, ...filters }); setItems((current) => [...current, ...result.results.filter((item) => !current.some((known) => known.id === item.id))]); setHasNext(result.hasNext); setNextPage((page) => page + 1); } catch (requestError) { setError(requestError); } finally { setLoadingMore(false); } }
  return { data, items, setItems, hasNext, loadingMore, error, setError, loadMore };
}

export function CreatorQuestions() {
  const [status, setStatus] = useState("");
  const questions = usePagedManagement(managementApi.listQuestions, { status });
  const nodes = useAsyncData(allNodes, []);
  const [createOpen, setCreateOpen] = useState(false); const [message, setMessage] = useState("");
  if (questions.data.loading || nodes.loading) return <LoadingPanel />;
  if (questions.data.error || nodes.error) return <ErrorPanel message={questions.data.error || nodes.error} onRetry={() => { questions.data.reload(); nodes.reload(); }} />;
  return <Page title="Creator studio" subtitle="Create and revise assessment questions in the scopes you are authorized for. Correct answers never enter student assessment state."><CreatorTabs /><CreatorNotice error={questions.error} message={message} onRetry={questions.data.reload} /><section className="community-top"><article className="panel community-composer"><p className="eyebrow">Question bank</p><h2>Creator-only questions</h2><p>Options and correct answers stay inside this creator route and come only from the management API.</p><button className="btn btn-primary" type="button" onClick={() => setCreateOpen((open) => !open)}><Icon name="plus" size={16} /> {createOpen ? "Close form" : "Create question"}</button>{createOpen && <QuestionForm nodes={nodes.data} onSaved={(created) => { questions.setItems((current) => [created, ...current]); setCreateOpen(false); setMessage("The question draft was created."); }} />}</article><article className="panel announcement-panel"><div className="panel-title"><h2>Workflow filter</h2><span>{questions.items.length}</span></div><label className="field"><span>Visible status</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option>{["draft", "in_review", "published", "rejected", "retired"].map((value) => <option value={value} key={value}>{humanize(value)}</option>)}</select></label></article></section><ManagementQuestionList items={questions.items} hasNext={questions.hasNext} loadingMore={questions.loadingMore} onLoadMore={questions.loadMore} /></Page>;
}

function ManagementQuestionList({ items, hasNext, loadingMore, onLoadMore }) {
  return <section className="panel community-post-list"><div className="panel-title"><h2>Visible questions</h2><span>{items.length}</span></div>{items.length ? items.map((item) => <article className="list-row" key={item.id}><span className="stat-icon"><Icon name="help" /></span><div><h2>{item.current_version?.prompt || "Untitled question"}</h2><p>{item.current_version?.academic_node_title || "Education scope"} · {humanize(item.current_version?.difficulty)} · revision {item.revision}</p>{item.review_note && <small>Review note: {item.review_note}</small>}</div><div className="post-actions"><WorkflowStatus status={item.workflow_status} /><Link className="btn btn-soft compact" to={`/creator/questions/${item.id}`}>Open</Link></div></article>) : <EmptyState title="No questions visible" text="No management questions match this filter and your creator scope." />}{hasNext && <button className="btn btn-soft" type="button" disabled={loadingMore} onClick={() => { void onLoadMore(); }}>{loadingMore ? "Loading…" : "Load more questions"}</button>}</section>;
}

export function CreatorQuestionDetail() {
  const { questionId = "" } = useParams();
  const data = useAsyncData(async () => ({ item: await managementApi.getQuestion(questionId), nodes: await allNodes() }), [questionId]);
  const [item, setItem] = useState(null); const [nodes, setNodes] = useState([]); const [message, setMessage] = useState("");
  useEffect(() => { if (data.data) { setItem(data.data.item); setNodes(data.data.nodes); setMessage(""); } }, [data.data]);
  if (data.loading) return <LoadingPanel />;
  if (data.error || !item) return <ErrorPanel message={data.error || "This question could not be loaded."} onRetry={data.reload} />;
  return <Page title="Question detail" subtitle="Changes create a new revision and reset it to draft when allowed."><CreatorTabs /><Link className="back-link" to="/creator/questions"><Icon name="chevron-left" size={16} /> Questions</Link>{message && <CreatorNotice message={message} />}<section className="community-top"><article className="panel community-composer"><p className="eyebrow">Revision {item.revision}</p><QuestionForm key={`${item.id}-${item.revision}`} item={item} nodes={nodes} onSaved={(updated) => { setItem(updated); setMessage("A new question revision was saved."); }} /></article><article className="panel announcement-panel"><LifecycleActions domain="question" record={item} onUpdated={(updated, conflict) => { if (updated) { setItem(updated); setMessage("The question workflow was updated."); } if (conflict) { setMessage("This question changed elsewhere. The latest server version is loading."); data.reload(); } }} />{item.review_note && <p className="save-hint">Review note: {item.review_note}</p>}</article></section></Page>;
}

function QuestionForm({ item = null, nodes, onSaved }) {
  const [form, setForm] = useState(() => questionState(item)); const [pending, setPending] = useState(false); const [error, setError] = useState(null);
  function change(key, value) { setForm((current) => ({ ...current, [key]: value })); }
  async function submit(event) { event.preventDefault(); if (pending) return; setPending(true); setError(null); try { const saved = item ? await managementApi.updateQuestion(item.id, { ...form, expectedRevision: item.revision }) : await managementApi.createQuestion(form); onSaved?.(saved); } catch (requestError) { setError(requestError); } finally { setPending(false); } }
  return <form className="composer-form" onSubmit={submit}><NodePicker nodes={nodes} value={form.academicNodeId} onChange={(value) => change("academicNodeId", value)} /><FieldError error={error} field="academic_node_id" /><label className="field"><span>Question type</span><select value={form.questionType} onChange={(event) => change("questionType", event.target.value)}>{QUESTION_TYPES.map((type) => <option value={type} key={type}>{humanize(type)}</option>)}</select></label><label className="field"><span>Prompt</span><textarea value={form.prompt} maxLength={10000} required onChange={(event) => change("prompt", event.target.value)} /></label><FieldError error={error} field="prompt" /><label className="field"><span>Explanation (shown only once the result is released)</span><textarea value={form.explanation} maxLength={10000} onChange={(event) => change("explanation", event.target.value)} /></label><label className="field"><span>Difficulty</span><select value={form.difficulty} onChange={(event) => change("difficulty", event.target.value)}>{DIFFICULTIES.map((difficulty) => <option key={difficulty} value={difficulty}>{humanize(difficulty)}</option>)}</select></label><label className="field"><span>Language</span><input value={form.language} maxLength={12} required onChange={(event) => change("language", event.target.value)} /></label><QuestionOptionsEditor options={form.options} onChange={(options) => change("options", options)} error={error} /><CreatorNotice error={error} /><button className="btn btn-primary" type="submit" disabled={pending}>{pending ? "Saving…" : item ? "Save new revision" : "Create question draft"}</button></form>;
}

export function CreatorQuizzes() {
  const [status, setStatus] = useState(""); const quizzes = usePagedManagement(managementApi.listQuizzes, { status }); const [createOpen, setCreateOpen] = useState(false); const [message, setMessage] = useState("");
  const choices = useAsyncData(async () => ({ nodes: await allNodes(), questions: await allQuestions() }), []);
  if (quizzes.data.loading || choices.loading) return <LoadingPanel />;
  if (quizzes.data.error || choices.error) return <ErrorPanel message={quizzes.data.error || choices.error} onRetry={() => { quizzes.data.reload(); choices.reload(); }} />;
  return <Page title="Creator studio" subtitle="Build quizzes without calculating results, access, ranking or mastery in the browser."><CreatorTabs /><CreatorNotice error={quizzes.error} message={message} onRetry={quizzes.data.reload} /><section className="community-top"><article className="panel community-composer"><p className="eyebrow">Quiz studio</p><h2>Assessment definitions</h2><p>Question availability, scope, publication state, delivery, scores, and release remain server authority.</p><button className="btn btn-primary" type="button" onClick={() => setCreateOpen((open) => !open)}><Icon name="plus" size={16} /> {createOpen ? "Close form" : "Create quiz"}</button>{createOpen && <QuizForm nodes={choices.data.nodes} questions={choices.data.questions} onSaved={(created) => { quizzes.setItems((current) => [created, ...current]); setCreateOpen(false); setMessage("The quiz draft was created."); }} />}</article><article className="panel announcement-panel"><div className="panel-title"><h2>Workflow filter</h2><span>{quizzes.items.length}</span></div><label className="field"><span>Visible status</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option>{["draft", "in_review", "published", "rejected", "retired"].map((value) => <option value={value} key={value}>{humanize(value)}</option>)}</select></label></article></section><section className="panel community-post-list"><div className="panel-title"><h2>Visible quizzes</h2><span>{quizzes.items.length}</span></div>{quizzes.items.length ? quizzes.items.map((item) => <article className="list-row" key={item.id}><span className="stat-icon"><Icon name="target" /></span><div><h2>{item.current_version?.title || "Untitled quiz"}</h2><p>{item.current_version?.academic_node_title || "Education scope"} · {humanize(item.current_version?.mode)} · {item.current_version?.question_count || 0} questions · revision {item.revision}</p>{item.review_note && <small>Review note: {item.review_note}</small>}</div><div className="post-actions"><WorkflowStatus status={item.workflow_status} /><Link className="btn btn-soft compact" to={`/creator/quizzes/${item.id}`}>Open</Link></div></article>) : <EmptyState title="No quizzes visible" text="No quizzes match this filter and your creator scope." />}{quizzes.hasNext && <button className="btn btn-soft" type="button" disabled={quizzes.loadingMore} onClick={() => { void quizzes.loadMore(); }}>{quizzes.loadingMore ? "Loading…" : "Load more quizzes"}</button>}</section></Page>;
}

export function CreatorQuizDetail() {
  const { quizId = "" } = useParams(); const data = useAsyncData(async () => ({ item: await managementApi.getQuiz(quizId), nodes: await allNodes(), questions: await allQuestions() }), [quizId]); const [item, setItem] = useState(null); const [choices, setChoices] = useState({ nodes: [], questions: [] }); const [message, setMessage] = useState("");
  useEffect(() => { if (data.data) { setItem(data.data.item); setChoices({ nodes: data.data.nodes, questions: data.data.questions }); setMessage(""); } }, [data.data]);
  if (data.loading) return <LoadingPanel />;
  if (data.error || !item) return <ErrorPanel message={data.error || "This quiz could not be loaded."} onRetry={data.reload} />;
  return <Page title="Quiz detail" subtitle="The complete quiz contract is submitted with the current expected revision."><CreatorTabs /><Link className="back-link" to="/creator/quizzes"><Icon name="chevron-left" size={16} /> Quizzes</Link>{message && <CreatorNotice message={message} />}<section className="community-top"><article className="panel community-composer"><p className="eyebrow">Revision {item.revision}</p><QuizForm key={`${item.id}-${item.revision}`} item={item} nodes={choices.nodes} questions={choices.questions} onSaved={(updated) => { setItem(updated); setMessage("A new quiz revision was saved."); }} /></article><article className="panel announcement-panel"><LifecycleActions domain="quiz" record={item} onUpdated={(updated, conflict) => { if (updated) { setItem(updated); setMessage("The quiz workflow was updated."); } if (conflict) { setMessage("This quiz changed elsewhere. The latest server version is loading."); data.reload(); } }} />{item.review_note && <p className="save-hint">Review note: {item.review_note}</p>}</article></section></Page>;
}

function QuizForm({ item = null, nodes, questions, onSaved }) {
  const [form, setForm] = useState(() => quizState(item)); const [pending, setPending] = useState(false); const [error, setError] = useState(null);
  function change(key, value) { setForm((current) => ({ ...current, [key]: value })); }
  function toggleDifficulty(value) { change("allowedDifficulties", form.allowedDifficulties.includes(value) ? form.allowedDifficulties.filter((item) => item !== value) : [...form.allowedDifficulties, value]); }
  async function submit(event) { event.preventDefault(); if (pending) return; setPending(true); setError(null); const data = { ...form, questionIds: form.selectionMode === "fixed" ? form.questionIds : [], availableFrom: isoDateTime(form.availableFrom), availableUntil: isoDateTime(form.availableUntil), ...(item ? { expectedRevision: item.revision } : {}) }; try { const saved = item ? await managementApi.updateQuiz(item.id, data) : await managementApi.createQuiz(data); onSaved?.(saved); } catch (requestError) { setError(requestError); } finally { setPending(false); } }
  const compactForm = typeof window !== "undefined" && window.innerWidth <= 639;
  return <form className="composer-form creator-quiz-form" onSubmit={submit}>
    <details className="creator-form-stage" open>
      <summary><span>1</span><strong>Quiz basics</strong><small>Title, academic location, and mode</small></summary>
      <div className="creator-form-stage-content"><NodePicker nodes={nodes} value={form.academicNodeId} onChange={(value) => change("academicNodeId", value)} /><FieldError error={error} field="academic_node_id" /><label className="field"><span>Quiz title</span><input value={form.title} maxLength={220} required onChange={(event) => change("title", event.target.value)} /></label><FieldError error={error} field="title" /><label className="field"><span>Instructions (optional)</span><textarea value={form.instructions} maxLength={10000} onChange={(event) => change("instructions", event.target.value)} /></label><label className="field"><span>Mode</span><select value={form.mode} onChange={(event) => change("mode", event.target.value)}>{QUIZ_MODES.map((mode) => <option value={mode} key={mode}>{humanize(mode)}</option>)}</select></label></div>
    </details>
    <details className="creator-form-stage" open={!compactForm}>
      <summary><span>2</span><strong>Questions</strong><small>{form.questionCount} selected target</small></summary>
      <div className="creator-form-stage-content"><label className="field"><span>Question selection</span><select value={form.selectionMode} onChange={(event) => change("selectionMode", event.target.value)}>{QUIZ_SELECTION_MODES.map((mode) => <option value={mode} key={mode}>{humanize(mode)}</option>)}</select></label><label className="field"><span>Question count</span><input type="number" min="1" max="100" value={form.questionCount} required onChange={(event) => change("questionCount", event.target.value)} /></label><FieldError error={error} field="question_count" /><QuizQuestionPicker questions={questions} selectedIds={form.questionIds} onChange={(value) => change("questionIds", value)} selectionMode={form.selectionMode} error={error} /></div>
    </details>
    <details className="creator-form-stage" open={!compactForm}>
      <summary><span>3</span><strong>Timing and release</strong><small>Availability, attempts, and pass mark</small></summary>
      <div className="creator-form-stage-content"><label className="field"><span>Duration in seconds (required for quiz and mastery)</span><input type="number" min="60" max="14400" value={form.durationSeconds} onChange={(event) => change("durationSeconds", event.target.value)} /></label><label className="field"><span>Maximum attempts (0 means unlimited)</span><input type="number" min="0" max="100" value={form.maximumAttempts} required onChange={(event) => change("maximumAttempts", event.target.value)} /></label><label className="field"><span>Available from (optional)</span><input type="datetime-local" value={form.availableFrom} onChange={(event) => change("availableFrom", event.target.value)} /></label><label className="field"><span>Available until (required for delayed results)</span><input type="datetime-local" value={form.availableUntil} onChange={(event) => change("availableUntil", event.target.value)} /></label><label className="field"><span>Result release</span><select value={form.resultRelease} onChange={(event) => change("resultRelease", event.target.value)}>{RESULT_RELEASES.map((release) => <option key={release} value={release}>{humanize(release)}</option>)}</select></label><label className="field"><span>Pass percent</span><input type="number" min="0" max="100" step="0.01" value={form.passPercent} required onChange={(event) => change("passPercent", event.target.value)} /></label></div>
    </details>
    <details className="creator-form-stage" open={!compactForm}>
      <summary><span>4</span><strong>Eligibility and pool</strong><small>Randomization, rewards, and difficulty</small></summary>
      <div className="creator-form-stage-content"><div className="composer-form"><label className="check-row"><input type="checkbox" checked={form.randomizeQuestions} onChange={(event) => change("randomizeQuestions", event.target.checked)} /> Randomize questions</label><label className="check-row"><input type="checkbox" checked={form.randomizeOptions} onChange={(event) => change("randomizeOptions", event.target.checked)} /> Randomize options</label><label className="check-row"><input type="checkbox" checked={form.rankingEligible} onChange={(event) => change("rankingEligible", event.target.checked)} /> Ranking eligible</label><label className="check-row"><input type="checkbox" checked={form.achievementEligible} onChange={(event) => change("achievementEligible", event.target.checked)} /> Achievement eligible</label><label className="check-row"><input type="checkbox" checked={form.focusRequired} onChange={(event) => change("focusRequired", event.target.checked)} /> Require focus workspace</label></div><section className="composer-form"><div className="panel-title"><h2>Pool difficulties</h2><span>{form.allowedDifficulties.length}</span></div>{DIFFICULTIES.map((difficulty) => <label className="check-row" key={difficulty}><input type="checkbox" checked={form.allowedDifficulties.includes(difficulty)} onChange={() => toggleDifficulty(difficulty)} /> {humanize(difficulty)}</label>)}</section><label className="field"><span>Language</span><input value={form.language} maxLength={12} required onChange={(event) => change("language", event.target.value)} /></label></div>
    </details>
    <CreatorNotice error={error} /><button className="btn btn-primary" type="submit" disabled={pending}>{pending ? "Saving…" : item ? "Save new revision" : "Create quiz draft"}</button>
  </form>;
}
