# Generated by Django 5.2.16 on 2026-07-18 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_generalize_auth_attempt_throttling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('version', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=120)),
                ('qualifying_activity_types', models.JSONField(default=list)),
                ('boundary_timezone', models.CharField(default='UTC', max_length=64)),
                ('grace_days', models.PositiveSmallIntegerField(default=0)),
                ('freeze_tokens_enabled', models.BooleanField(default=False)),
                ('recovery_window_days', models.PositiveSmallIntegerField(default=0)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('code', '-version'),
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='streak_policy_version_unique'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('code',), name='streak_one_active_policy')],
            },
        ),
        migrations.CreateModel(
            name='StreakActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=180)),
                ('activity_type', models.CharField(max_length=64)),
                ('source_object_id', models.UUIDField(blank=True, null=True)),
                ('qualified_on', models.DateField()),
                ('occurred_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streak_activities', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='streaks.streakpolicy')),
            ],
            options={
                'ordering': ('-qualified_on', '-occurred_at', '-id'),
                'indexes': [models.Index(fields=['user', 'qualified_on'], name='streak_user_day_idx'), models.Index(fields=['activity_type', 'occurred_at'], name='streak_type_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'source_key'), name='streak_user_source_unique')],
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='streak_state', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('current_days', models.PositiveIntegerField(default=0)),
                ('longest_days', models.PositiveIntegerField(default=0)),
                ('last_qualified_on', models.DateField(blank=True, null=True)),
                ('freeze_tokens_available', models.PositiveSmallIntegerField(default=0)),
                ('grace_days_used', models.PositiveSmallIntegerField(default=0)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='streaks.streakpolicy')),
            ],
            options={
                'indexes': [models.Index(fields=['-current_days', 'user'], name='streak_current_user_idx')],
            },
        ),
    ]
