# Generated by Django 5.2.16 on 2026-07-18 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_generalize_auth_attempt_throttling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XpBalance',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='xp_balance', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_points', models.BigIntegerField(default=0)),
                ('ranking_points', models.BigIntegerField(default=0)),
                ('transaction_count', models.PositiveBigIntegerField(default=0)),
                ('last_awarded_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('total_points__gte', 0)), name='xp_balance_total_gte_zero'), models.CheckConstraint(condition=models.Q(('ranking_points__gte', 0)), name='xp_balance_rank_gte_zero')],
            },
        ),
        migrations.CreateModel(
            name='XpTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=180)),
                ('source_event_id', models.UUIDField(blank=True, null=True)),
                ('source_event_name', models.CharField(max_length=100)),
                ('source_object_id', models.UUIDField(blank=True, null=True)),
                ('rule_code', models.CharField(max_length=80)),
                ('rule_version', models.PositiveSmallIntegerField(default=1)),
                ('points', models.SmallIntegerField()),
                ('category', models.CharField(max_length=32)),
                ('reason', models.CharField(max_length=180)),
                ('ranking_eligible', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='xp.xptransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['user', '-occurred_at', '-id'], name='xp_user_time_idx'), models.Index(fields=['ranking_eligible', 'occurred_at', 'user'], name='xp_rank_time_user_idx'), models.Index(fields=['source_event_name', 'source_object_id'], name='xp_source_obj_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'source_key', 'rule_code'), name='xp_user_source_rule_unique'), models.CheckConstraint(condition=models.Q(('points', 0), _negated=True), name='xp_points_nonzero')],
            },
        ),
    ]
