# Generated by Django 5.2.16 on 2026-07-18 03:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('product__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=320)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=320)),
                ('audience', models.CharField(choices=[('individual', 'Individual'), ('family', 'Family (future)'), ('organization', 'Organization (future)'), ('institution', 'Institution (future)')], default='individual', max_length=16)),
                ('trial_days', models.PositiveSmallIntegerField(default=0)),
                ('grace_days', models.PositiveSmallIntegerField(default=0)),
                ('terms', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='product_catalog.plan')),
            ],
            options={
                'ordering': ('plan__code', '-version'),
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='current_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='product_catalog.planversion'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('region_code', models.CharField(blank=True, max_length=2)),
                ('interval', models.CharField(choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year')], max_length=8)),
                ('interval_count', models.PositiveSmallIntegerField(default=1)),
                ('tax_behavior', models.CharField(choices=[('unspecified', 'Unspecified'), ('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], default='unspecified', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='product_catalog.planversion')),
            ],
            options={
                'ordering': ('currency', 'region_code', 'amount_minor'),
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='product_catalog.product'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.UniqueConstraint(fields=('plan', 'version'), name='catalog_plan_version_unique'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['plan_version', 'status', 'currency', 'region_code'], name='catalog_price_offer_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['status', 'valid_until'], name='catalog_price_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='catalog_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('interval_count__gt', 0)), name='catalog_price_interval_positive'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_from__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='catalog_price_valid_window'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['product', 'status'], name='catalog_plan_status_idx'),
        ),
    ]
