# Generated by Django 5.2.16 on 2026-07-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0002_seed_trial_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='currency_exponent',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('currency_exponent__lte', 4)), name='catalog_currency_exponent_valid'),
        ),
    ]
