# Generated by Django 5.2.16 on 2026-07-15 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('institution', 'Institution'), ('college', 'College or faculty'), ('department', 'Department'), ('academic_year', 'Academic year'), ('semester', 'Semester'), ('subject', 'Subject'), ('unit', 'Unit or chapter'), ('lesson', 'Lesson')], max_length=24)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('path', models.CharField(editable=False, max_length=2048, unique=True)),
                ('depth', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('is_discoverable', models.BooleanField(default=False, editable=False)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='education.educationnode')),
            ],
            options={
                'ordering': ('position', 'title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CreatorScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_create_content', models.BooleanField(default=True)),
                ('can_review_content', models.BooleanField(default=False)),
                ('can_publish_content', models.BooleanField(default=False)),
                ('can_manage_hierarchy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_education_scopes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_scopes', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_scopes', to='education.educationnode')),
            ],
            options={
                'ordering': ('node__path', 'user_id'),
            },
        ),
        migrations.AddIndex(
            model_name='educationnode',
            index=models.Index(fields=['parent', 'is_discoverable', 'position'], name='edu_parent_discovery_idx'),
        ),
        migrations.AddIndex(
            model_name='educationnode',
            index=models.Index(fields=['kind', 'is_discoverable', 'title'], name='edu_kind_discovery_idx'),
        ),
        migrations.AddIndex(
            model_name='educationnode',
            index=models.Index(fields=['path'], name='edu_path_idx'),
        ),
        migrations.AddConstraint(
            model_name='educationnode',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'slug'), name='edu_sibling_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='educationnode',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('slug',), name='edu_root_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='educationnode',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='edu_node_not_own_parent'),
        ),
        migrations.AddIndex(
            model_name='creatorscope',
            index=models.Index(fields=['user', 'node'], name='edu_scope_user_node_idx'),
        ),
        migrations.AddConstraint(
            model_name='creatorscope',
            constraint=models.UniqueConstraint(fields=('user', 'node'), name='edu_creator_scope_unique'),
        ),
        migrations.AddConstraint(
            model_name='creatorscope',
            constraint=models.CheckConstraint(condition=models.Q(('can_create_content', True), ('can_review_content', True), ('can_publish_content', True), ('can_manage_hierarchy', True), _connector='OR'), name='edu_scope_has_capability'),
        ),
    ]
