# Generated by Django 5.2.16 on 2026-07-17 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='creatorscope',
            name='edu_scope_has_capability',
        ),
        migrations.AddField(
            model_name='creatorscope',
            name='can_create_assessments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creatorscope',
            name='can_publish_assessments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creatorscope',
            name='can_review_assessments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='creatorscope',
            constraint=models.CheckConstraint(condition=models.Q(('can_create_content', True), ('can_review_content', True), ('can_publish_content', True), ('can_create_assessments', True), ('can_review_assessments', True), ('can_publish_assessments', True), ('can_manage_hierarchy', True), _connector='OR'), name='edu_scope_has_capability'),
        ),
    ]
