# Generated by Django 5.2.16 on 2026-07-18 03:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectible', 'Uncollectible'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded')], max_length=24)),
                ('currency', models.CharField(max_length=3)),
                ('subtotal_minor', models.PositiveBigIntegerField()),
                ('discount_minor', models.PositiveBigIntegerField(default=0)),
                ('tax_minor', models.PositiveBigIntegerField(default=0)),
                ('total_minor', models.PositiveBigIntegerField()),
                ('amount_paid_minor', models.PositiveBigIntegerField(default=0)),
                ('amount_refunded_minor', models.PositiveBigIntegerField(default=0)),
                ('period_started_at', models.DateTimeField(blank=True, null=True)),
                ('period_ends_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='subscriptions.subscriptionaccount')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='payments.payment')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ('-issued_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=240)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_amount_minor', models.PositiveBigIntegerField()),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('product_code', models.CharField(max_length=60)),
                ('plan_code', models.CharField(max_length=60)),
                ('price_code', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='invoices.invoice')),
            ],
            options={
                'ordering': ('line_number',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectible', 'Uncollectible'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded')], max_length=24)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectible', 'Uncollectible'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded')], max_length=24)),
                ('reason_code', models.CharField(max_length=80)),
                ('source_reference', models.CharField(max_length=180)),
                ('effective_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='invoices.invoice')),
            ],
            options={
                'ordering': ('effective_at', 'created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['account', '-issued_at'], name='invoice_account_time_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_at'], name='invoice_state_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_minor__gt', 0)), name='invoice_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid_minor__lte', models.F('total_minor'))), name='invoice_paid_not_over_total'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_refunded_minor__lte', models.F('amount_paid_minor'))), name='invoice_refund_not_over_paid'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('period_ends_at__isnull', True), ('period_started_at__isnull', True), ('period_ends_at__gt', models.F('period_started_at')), _connector='OR'), name='invoice_period_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(fields=('invoice', 'line_number'), name='invoice_line_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='invoice_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_amount_minor__gt', 0)), name='invoice_line_unit_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='invoice_line_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoicetransition',
            constraint=models.UniqueConstraint(fields=('invoice', 'source_reference'), name='invoice_transition_source_unique'),
        ),
    ]
