# Generated by Django 5.2.16 on 2026-07-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('payments', '0001_initial'),
        ('subscriptions', '0002_backfill_verified_trials'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency_exponent',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('currency_exponent__lte', 4)), name='invoice_currency_exponent_valid'),
        ),
    ]
