# Generated by Django 5.2.16 on 2026-07-18 03:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_catalog', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('refunded_amount_minor', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded')], default='initiated', max_length=24)),
                ('idempotency_key', models.CharField(max_length=180)),
                ('price_snapshot', models.JSONField()),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('initiated_at', models.DateTimeField()),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.subscriptionaccount')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='product_catalog.price')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded')], max_length=24)),
                ('to_status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded')], max_length=24)),
                ('source', models.CharField(choices=[('system', 'System'), ('provider', 'Verified provider event'), ('refund', 'Refund'), ('reconciliation', 'Reconciliation')], max_length=16)),
                ('reason_code', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(max_length=180)),
                ('source_reference', models.CharField(blank=True, max_length=180)),
                ('effective_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='payments.payment')),
            ],
            options={
                'ordering': ('effective_at', 'created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['account', 'status', '-created_at'], name='payment_account_state_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['subscription', 'status', '-created_at'], name='payment_subscription_state_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payment_state_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('account', 'idempotency_key'), name='payment_account_idempotent'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount_minor__lte', models.F('amount_minor'))), name='payment_refund_not_over_amount'),
        ),
        migrations.AddIndex(
            model_name='paymenttransition',
            index=models.Index(fields=['payment', '-effective_at'], name='payment_transition_time_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransition',
            index=models.Index(fields=['source', 'source_reference'], name='payment_transition_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransition',
            constraint=models.UniqueConstraint(fields=('payment', 'idempotency_key'), name='payment_transition_idempotent'),
        ),
    ]
