# Generated by Django 5.2.17 on 2026-10-08 14:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_revenue_time_index'),
        ('product_catalog', '0007_dentistry_term_plans'),
        ('subscriptions', '0003_payment_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='installment_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InstallmentAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('currency_exponent', models.PositiveSmallIntegerField(default=3)),
                ('installment_amounts_minor', models.JSONField()),
                ('anchor_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Paid in full'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_agreements', to='subscriptions.subscriptionaccount')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_agreements', to='product_catalog.price')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_agreements', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='installment_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.installmentagreement'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'succeeded'))), fields=('installment_agreement', 'installment_number'), name='payment_installment_once'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('installment_agreement__isnull', True), ('installment_number__isnull', True)), models.Q(('installment_agreement__isnull', False), ('installment_number__gte', 1)), _connector='OR'), name='payment_installment_numbered'),
        ),
        migrations.AddIndex(
            model_name='installmentagreement',
            index=models.Index(fields=['subscription', 'status'], name='installment_subscription_idx'),
        ),
        migrations.AddConstraint(
            model_name='installmentagreement',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('account',), name='installment_one_active_per_account'),
        ),
        migrations.AddConstraint(
            model_name='installmentagreement',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount_minor__gt', 0)), name='installment_total_positive'),
        ),
    ]
