# Generated by Django 5.2.16 on 2026-07-15 03:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_type', models.CharField(choices=[('independent', 'Independent'), ('study', 'Study'), ('quiz', 'Quiz')], default='independent', max_length=16)),
                ('context_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('planned_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('active_duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='FocusSessionActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('activity_type', models.CharField(choices=[('started', 'Started'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], max_length=16)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='focus.focussession')),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['user', '-started_at'], name='focus_user_started_idx'),
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['status', '-started_at'], name='focus_status_started_idx'),
        ),
        migrations.AddConstraint(
            model_name='focussession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('context_id__isnull', True), ('context_type', 'independent')), models.Q(models.Q(('context_type', 'independent'), _negated=True), ('context_id__isnull', False)), _connector='OR'), name='focus_context_reference_valid'),
        ),
        migrations.AddConstraint(
            model_name='focussession',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='focus_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='focussession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('status__in', ('active', 'paused'))), models.Q(('ended_at__isnull', False), ('status__in', ('completed', 'abandoned'))), _connector='OR'), name='focus_status_end_consistent'),
        ),
        migrations.AddIndex(
            model_name='focussessionactivity',
            index=models.Index(fields=['session', 'occurred_at'], name='focus_timeline_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='focussessionactivity',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='focus_timeline_sequence_unique'),
        ),
    ]
