# Generated by Django 5.2.16 on 2026-07-18 20:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('tool', models.CharField(max_length=32)),
                ('layer_key', models.CharField(default='personal', max_length=64)),
                ('bounds', models.JSONField(default=dict)),
                ('payload', models.JSONField(default=dict)),
                ('color', models.CharField(max_length=16)),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=6)),
                ('opacity', models.DecimalField(decimal_places=3, max_digits=4)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('page_number', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FocusAnnotationCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField()),
                ('document_version_id', models.UUIDField()),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FocusSyncReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField()),
                ('request_digest', models.CharField(max_length=64)),
                ('response_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FocusWorkspaceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField()),
                ('document_version_id', models.UUIDField()),
                ('file_id', models.UUIDField()),
                ('current_page', models.PositiveIntegerField(default=1)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('zoom', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('sidebar', models.CharField(choices=[('closed', 'Closed'), ('thumbnails', 'Thumbnails'), ('notes', 'Notes')], default='closed', max_length=16)),
                ('active_tool', models.CharField(blank=True, max_length=32)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('open_tabs', models.JSONField(blank=True, default=list)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='focussession',
            name='client_instance_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='focussession',
            name='last_activity_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='focussession',
            name='revision',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['user', 'status', '-last_activity_at'], name='focus_user_activity_idx'),
        ),
        migrations.AddConstraint(
            model_name='focussession',
            constraint=models.UniqueConstraint(condition=models.Q(('client_instance_id__isnull', False)), fields=('user', 'client_instance_id'), name='focus_user_client_instance_unique'),
        ),
        migrations.AddField(
            model_name='focusannotationcollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_annotation_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='focusannotation',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='focus.focusannotationcollection'),
        ),
        migrations.AddField(
            model_name='focussyncreceipt',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_receipts', to='focus.focusannotationcollection'),
        ),
        migrations.AddField(
            model_name='focussyncreceipt',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sync_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='focusworkspacesnapshot',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='focus.focussession'),
        ),
        migrations.AddField(
            model_name='focusworkspacesnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='focusannotationcollection',
            index=models.Index(fields=['user', 'document_version_id'], name='focus_annotation_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='focusannotationcollection',
            constraint=models.UniqueConstraint(fields=('user', 'document_version_id'), name='focus_annotation_collection_unique'),
        ),
        migrations.AddIndex(
            model_name='focusannotation',
            index=models.Index(fields=['collection', 'page_number', 'deleted_at'], name='focus_annotation_page_idx'),
        ),
        migrations.AddIndex(
            model_name='focusannotation',
            index=models.Index(fields=['collection', 'updated_at'], name='focus_annotation_sync_idx'),
        ),
        migrations.AddConstraint(
            model_name='focusannotation',
            constraint=models.CheckConstraint(condition=models.Q(('page_number__gte', 1)), name='focus_annotation_page_positive'),
        ),
        migrations.AddConstraint(
            model_name='focusannotation',
            constraint=models.CheckConstraint(condition=models.Q(('thickness__gt', Decimal('0')), ('thickness__lte', Decimal('64'))), name='focus_annotation_thickness_range'),
        ),
        migrations.AddConstraint(
            model_name='focusannotation',
            constraint=models.CheckConstraint(condition=models.Q(('opacity__gte', Decimal('0')), ('opacity__lte', Decimal('1'))), name='focus_annotation_opacity_range'),
        ),
        migrations.AddIndex(
            model_name='focussyncreceipt',
            index=models.Index(fields=['collection', '-created_at'], name='focus_sync_receipt_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='focussyncreceipt',
            constraint=models.UniqueConstraint(fields=('collection', 'idempotency_key'), name='focus_sync_receipt_unique'),
        ),
        migrations.AddIndex(
            model_name='focusworkspacesnapshot',
            index=models.Index(fields=['user', 'document_version_id', '-updated_at'], name='focus_workspace_restore_idx'),
        ),
        migrations.AddConstraint(
            model_name='focusworkspacesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('current_page__gte', 1)), name='focus_workspace_page_positive'),
        ),
        migrations.AddConstraint(
            model_name='focusworkspacesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('page_count__isnull', True), ('page_count__gte', 1), _connector='OR'), name='focus_workspace_page_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='focusworkspacesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('zoom__gte', Decimal('0.50')), ('zoom__lte', Decimal('4.00'))), name='focus_workspace_zoom_range'),
        ),
    ]
