# Generated by Django 5.2.17 on 2026-09-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0009_annotation_logical_sheet_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activestudyrun',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=16),
        ),
    ]
