# Generated by Django 5.2.17 on 2026-09-15 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_activestudysettings_edition_catalogdocument_edition_and_more'),
        ('focus', '0010_alter_activestudyrun_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activestudyrun',
            name='active_study_one_active_run_per_sheet',
        ),
        migrations.AddField(
            model_name='activestudyrun',
            name='edition',
            field=models.CharField(default='university', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='activestudyrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'sheet', 'difficulty', 'edition'), name='active_study_one_active_run_per_sheet'),
        ),
    ]
