# Generated by Django 5.2.17 on 2026-09-15 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0011_remove_activestudyrun_active_study_one_active_run_per_sheet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='focusworkspacesnapshot',
            index=models.Index(fields=['user', 'document_id', '-updated_at'], name='focus_workspace_doc_idx'),
        ),
    ]
