# Generated by Django 5.2.17 on 2026-09-26 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_paper_workspace_media'),
        ('focus', '0012_focusworkspacesnapshot_focus_workspace_doc_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperWorkspaceMedia',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('focal_x', models.PositiveSmallIntegerField(default=50)),
                ('focal_y', models.PositiveSmallIntegerField(default=50)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managed_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.managedfile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='focus_paper_media_singleton'), models.CheckConstraint(condition=models.Q(('focal_x__lte', 100), ('focal_y__lte', 100)), name='focus_paper_media_focal_range')],
            },
        ),
    ]
