# Generated by Django 5.2.17 on 2026-09-26 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def carry_over_player_media(apps, schema_editor):  # type: ignore[no-untyped-def]
    """The single Paper Workspace background becomes the first Lo-Fi scene.

    Its file, focal point and on/off state carry over unchanged, so students
    see exactly what they saw before; no file is copied.
    """

    PaperWorkspaceMedia = apps.get_model("focus", "PaperWorkspaceMedia")
    LofiScene = apps.get_model("focus", "LofiScene")
    media = PaperWorkspaceMedia.objects.filter(id=1, managed_file__isnull=False).first()
    if media is None:
        return
    LofiScene.objects.create(
        title="Lock-in Lo-Fi",
        media_file_id=media.managed_file_id,
        enabled=media.enabled,
        position=0,
        focal_x=media.focal_x,
        focal_y=media.focal_y,
        created_by_id=media.updated_by_id,
        updated_by_id=media.updated_by_id,
    )


def restore_player_media(apps, schema_editor):  # type: ignore[no-untyped-def]
    PaperWorkspaceMedia = apps.get_model("focus", "PaperWorkspaceMedia")
    LofiScene = apps.get_model("focus", "LofiScene")
    scene = LofiScene.objects.order_by("position", "created_at").first()
    if scene is None:
        return
    PaperWorkspaceMedia.objects.update_or_create(
        id=1,
        defaults={
            "managed_file_id": scene.media_file_id,
            "enabled": scene.enabled,
            "focal_x": scene.focal_x,
            "focal_y": scene.focal_y,
            "updated_by_id": scene.updated_by_id,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_managedfile_duration'),
        ('focus', '0013_paper_workspace_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LofiScene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('focal_x', models.PositiveSmallIntegerField(default=50)),
                ('focal_y', models.PositiveSmallIntegerField(default=50)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.managedfile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.managedfile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.RunPython(carry_over_player_media, restore_player_media),
        migrations.DeleteModel(
            name='PaperWorkspaceMedia',
        ),
        migrations.AddConstraint(
            model_name='lofiscene',
            constraint=models.CheckConstraint(condition=models.Q(('focal_x__lte', 100), ('focal_y__lte', 100)), name='focus_lofi_scene_focal_range'),
        ),
    ]
