# Generated by Django 5.2.17 on 2026-09-28 15:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0015_lock_in_lobby'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='focussession',
            name='lock_in_live',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FocusSessionParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('presence', models.CharField(choices=[('focused', 'Focused'), ('break', 'Break'), ('away', 'Away')], default='away', max_length=8)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('break_started_at', models.DateTimeField(blank=True, null=True)),
                ('break_seconds', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='focus.focussession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lock_in_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'left_at'], name='focus_participant_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'user'), name='focus_session_participant_unique')],
            },
        ),
    ]
