# Generated by Django 5.2.17 on 2026-09-29 13:17

import apps.biweekly.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiweeklySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('analysis', 'Analysis'), ('review', 'Review')], max_length=8)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('data', models.JSONField(default=dict)),
                ('pdf', models.FileField(blank=True, max_length=512, upload_to=apps.biweekly.models.report_upload_path)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biweekly_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-period_start', 'report_type'),
            },
        ),
        migrations.CreateModel(
            name='BiweeklyReviewTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='test', to='biweekly.biweeklysnapshot')),
            ],
        ),
        migrations.AddIndex(
            model_name='biweeklysnapshot',
            index=models.Index(fields=['user', 'report_type', '-period_start'], name='biweekly_history_idx'),
        ),
        migrations.AddConstraint(
            model_name='biweeklysnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'report_type', 'period_start'), name='biweekly_user_type_start_unique'),
        ),
        migrations.AddConstraint(
            model_name='biweeklysnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='biweekly_period_positive'),
        ),
    ]
