# Generated by Django 5.2.16 on 2026-07-18 03:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='requested', max_length=16)),
                ('reason', models.CharField(max_length=240)),
                ('idempotency_key', models.CharField(max_length=180)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('requested_at', models.DateTimeField()),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RefundTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('requested', 'Requested'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=16)),
                ('to_status', models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=16)),
                ('source', models.CharField(choices=[('admin', 'Administrator'), ('provider', 'Verified provider event'), ('reconciliation', 'Reconciliation')], max_length=16)),
                ('reason_code', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(max_length=180)),
                ('source_reference', models.CharField(blank=True, max_length=180)),
                ('effective_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='refunds.refund')),
            ],
            options={
                'ordering': ('effective_at', 'created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', 'status', '-requested_at'], name='refund_payment_state_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', 'requested_at'], name='refund_state_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(fields=('payment', 'idempotency_key'), name='refund_payment_idempotent'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='refund_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='refundtransition',
            index=models.Index(fields=['refund', '-effective_at'], name='refund_transition_time_idx'),
        ),
        migrations.AddIndex(
            model_name='refundtransition',
            index=models.Index(fields=['source', 'source_reference'], name='refund_transition_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='refundtransition',
            constraint=models.UniqueConstraint(fields=('refund', 'idempotency_key'), name='refund_transition_idempotent'),
        ),
    ]
