# Generated by Django 5.2.16 on 2026-07-18 03:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitlementDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=320)),
                ('value_type', models.CharField(choices=[('boolean', 'Boolean access'), ('quantity', 'Quantity limit'), ('configuration', 'Configuration')], default='boolean', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='EntitlementGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('subscription', 'Subscription'), ('manual', 'Administrator override'), ('promotion', 'Promotion (future)'), ('family', 'Family (future)'), ('organization', 'Organization (future)'), ('institution', 'Institution (future)')], max_length=16)),
                ('source_id', models.UUIDField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=12)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('quantity_limit', models.PositiveBigIntegerField(blank=True, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='entitlements.entitlementdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlement_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('entitlement__code', '-granted_at'),
            },
        ),
        migrations.CreateModel(
            name='EntitlementGrantAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('granted', 'Granted'), ('updated', 'Updated'), ('revoked', 'Revoked'), ('expired', 'Expired')], max_length=12)),
                ('reason_code', models.CharField(max_length=80)),
                ('source_reference', models.CharField(blank=True, max_length=160)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitlement_grant_actions', to=settings.AUTH_USER_MODEL)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='entitlements.entitlementgrant')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PlanEntitlementRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_limit', models.PositiveBigIntegerField(blank=True, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_rules', to='entitlements.entitlementdefinition')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlement_rules', to='product_catalog.planversion')),
            ],
        ),
        migrations.AddIndex(
            model_name='entitlementgrant',
            index=models.Index(fields=['user', 'entitlement', 'status', 'ends_at'], name='entitlement_access_check_idx'),
        ),
        migrations.AddIndex(
            model_name='entitlementgrant',
            index=models.Index(fields=['source_type', 'source_id', 'status'], name='entitlement_source_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='entitlementgrant',
            constraint=models.UniqueConstraint(fields=('user', 'entitlement', 'source_type', 'source_id'), name='entitlement_grant_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='entitlementgrant',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='entitlement_grant_window_valid'),
        ),
        migrations.AddIndex(
            model_name='entitlementgrantaudit',
            index=models.Index(fields=['grant', 'created_at'], name='entitlement_audit_time_idx'),
        ),
        migrations.AddIndex(
            model_name='planentitlementrule',
            index=models.Index(fields=['plan_version', 'entitlement'], name='entitlement_plan_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='planentitlementrule',
            constraint=models.UniqueConstraint(fields=('plan_version', 'entitlement'), name='entitlement_plan_rule_unique'),
        ),
    ]
