# Generated by Django 5.2.16 on 2026-07-18 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalActionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_code', models.CharField(max_length=80)),
                ('reason', models.CharField(max_length=500)),
                ('payload', models.JSONField(default=dict)),
                ('preview', models.JSONField(default=dict)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('confirmation_digest', models.CharField(editable=False, max_length=64)),
                ('status', models.CharField(choices=[('previewed', 'Previewed'), ('executing', 'Executing'), ('completed', 'Completed'), ('partial', 'Partially completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='previewed', max_length=12)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_action_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['requested_by', '-created_at'], name='operations_user_time_idx'), models.Index(fields=['action_code', 'status'], name='operations_action_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('requested_by', 'idempotency_key'), name='operations_user_idempotency_unique')],
            },
        ),
    ]
