import { memo } from "react";
import {
  Activity,
  AlertTriangle,
  Award,
  BarChart3,
  Bell,
  Bookmark,
  BookOpen,
  Brain,
  Calendar,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  Clock3,
  Eye,
  EyeOff,
  Globe,
  FileQuestion,
  FileText,
  Flame,
  Home,
  Layers,
  ListChecks,
  LockKeyhole,
  LogOut,
  Megaphone,
  Medal,
  Menu,
  MessageSquare,
  Microscope,
  Moon,
  Pencil,
  Plus,
  RotateCcw,
  Save,
  Search,
  ShieldAlert,
  Shuffle,
  Settings,
  Sparkles,
  Sun,
  Syringe,
  Target,
  Trophy,
  User,
  X,
  ArrowLeft,
  Maximize2,
  Highlighter,
  Eraser,
  Hand,
  Trash2,
  Minus,
  GripVertical,
  ChevronUp,
  Undo2,
  Redo2,
  Lasso,
  ZoomIn,
  MousePointer2,
  Shapes,
  Circle,
  Square,
  Snowflake,
  Triangle,
  ArrowUpRight,
  Move,
  Scissors,
  Type,
  ShoppingBag,
  Gift,
  Palette,
  Shirt,
  Headphones,
  Image,
  MousePointer,
  Sticker,
  Volume2,
  WandSparkles,
  PackageOpen,
  CircleDollarSign
} from "lucide-react";

const icons = {
  grip: GripVertical,
  "chevron-up": ChevronUp,
  minus: Minus,
  highlighter: Highlighter,
  eraser: Eraser,
  hand: Hand,
  trash: Trash2,
  "arrow-left": ArrowLeft,
  expand: Maximize2,
  activity: Activity,
  "alert-triangle": AlertTriangle,
  analytics: BarChart3,
  award: Award,
  bell: Bell,
  bookmark: Bookmark,
  "book-open": BookOpen,
  brain: Brain,
  calendar: Calendar,
  check: CheckCircle2,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  help: CircleHelp,
  clock: Clock3,
  eye: Eye,
  "eye-off": EyeOff,
  globe: Globe,
  "file-question": FileQuestion,
  file: FileText,
  flame: Flame,
  home: Home,
  layers: Layers,
  "list-checks": ListChecks,
  lock: LockKeyhole,
  logout: LogOut,
  megaphone: Megaphone,
  medal: Medal,
  menu: Menu,
  messages: MessageSquare,
  microscope: Microscope,
  moon: Moon,
  pencil: Pencil,
  plus: Plus,
  reset: RotateCcw,
  save: Save,
  search: Search,
  "shield-alert": ShieldAlert,
  shuffle: Shuffle,
  settings: Settings,
  sparkles: Sparkles,
  sun: Sun,
  syringe: Syringe,
  target: Target,
  trophy: Trophy,
  user: User,
  x: X,
  undo: Undo2,
  redo: Redo2,
  lasso: Lasso,
  "zoom-in": ZoomIn,
  pointer: MousePointer2,
  shapes: Shapes,
  circle: Circle,
  square: Square,
  snowflake: Snowflake,
  triangle: Triangle,
  "arrow-up-right": ArrowUpRight,
  move: Move,
  scissors: Scissors,
  type: Type,
  "shopping-bag": ShoppingBag,
  gift: Gift,
  palette: Palette,
  shirt: Shirt,
  headphones: Headphones,
  image: Image,
  cursor: MousePointer,
  sticker: Sticker,
  volume: Volume2,
  wand: WandSparkles,
  package: PackageOpen,
  coins: CircleDollarSign
};

/** @typedef {import("lucide-react").LucideProps & {name: string}} IconProps */
/**
 * Icons whose meaning is tied to the reading direction, so they have to face
 * the other way in Arabic. "Next" is on the left in an RTL layout, and a
 * chevron still pointing right sends the reader back where they came from.
 *
 * Everything else keeps its orientation: a flame, a clock or a trophy does not
 * turn around because the text does. Rotational icons are deliberately absent -
 * undo and redo describe a direction in time rather than in the page.
 */
const MIRRORED_IN_RTL = new Set(["chevron-left", "chevron-right", "arrow-left", "arrow-up-right", "logout"]);

/** @type {import("react").NamedExoticComponent<IconProps>} */
export const Icon = memo(function Icon({ name, size = 20, strokeWidth = 1.9, ...props }) {
  const Component = icons[name] || CircleHelp;
  // The flip itself is a stylesheet rule, so it follows the direction of the
  // element the icon actually sits in rather than a locale read at render time.
  const mirrored = MIRRORED_IN_RTL.has(name) ? "" : undefined;
  return <Component aria-hidden="true" size={size} strokeWidth={strokeWidth} data-mirror-rtl={mirrored} {...props} />;
});
